export const privacyNotice = {
  en: {
    heading: 'Visit counts, cookies, and analytics',
    paragraphs: [
      'The site counts each full page load, including reloads, without creating a browser identifier. Aggregate daily page-load totals for the last 365 UTC days and an all-time total are stored on the site server. Hosting providers may separately process IP addresses and technical access logs to deliver and secure the site.',
      'The unique-browser counter is enabled by default. On the first visit, the site sets a first-party, Secure, HttpOnly browser cookie named advs_visitor for up to 395 days. It contains a random value; the server stores its SHA-256 hash and most recent UTC visit date for up to 395 days after that visit. Counts cover browser profiles, not people. You can disable this counter in Privacy settings on this page. When disabled, the counter stops and the site requests deletion of this browser’s cookie and stored hash; the all-time aggregate remains. If deletion fails, the request is retried on a later page load while the counter stays disabled.',
      'Google Analytics, Yandex Metrica, Yandex Webvisor, and Microsoft Clarity also load by default, before you make a choice. These providers can receive page URLs, browser and device details, approximate location, clicks, scrolling, session information, cookies, and similar identifiers. Webvisor and Clarity may replay page interactions. They can process data outside your country according to their own policies. You can turn each service off in Privacy settings or use Decline all to turn off every optional service.',
      'The Privacy settings button is on this page. Customize opens individual switches showing your current selection; Save selection applies changes. Accept all enables every service. The × button only closes the panel without changing your selection. Your selection and its date are saved in localStorage and in the first-party advs_privacy_choice preference cookie for up to 395 days. This preference cookie contains settings and a timestamp, not a visitor identifier. A change is applied only if it can be saved in at least one of these places; otherwise the previous settings remain active. With no saved selection, all optional services are enabled. Theme and language preferences are also stored locally when selected. Disabling analytics prevents future loading after the page reloads; data already sent to a provider remains subject to its retention rules, and existing provider cookies may remain until removed in your browser. For privacy questions or data requests, use the contact links on the site.',
      'Site fonts are served from this site rather than requested from Google. The current games do not save personal game records between visits. If record saving is added, its storage and publication rules will be described before it is enabled.',
    ],
  },
  ru: {
    heading: 'Счётчики посещений, cookie и аналитика',
    paragraphs: [
      'Сайт считает каждую полную загрузку страницы, включая обновления, без присвоения номера браузеру. На сервере хранятся суммарные значения по дням UTC за последние 365 дней и общий итог. Хостинг может отдельно обрабатывать IP-адреса и технические журналы для работы и защиты сайта.',
      'Счётчик уникальных браузеров включён по умолчанию. При первом посещении сайт создаёт собственную защищённую cookie advs_visitor со случайным номером на срок до 395 дней. Сервер хранит хеш SHA-256 этого номера и дату последнего посещения по UTC не дольше 395 дней после него. Считаются браузерные профили, а не люди. Этот счётчик можно отключить в настройках конфиденциальности на этой странице. При отключении счётчик останавливается, а сайт запрашивает удаление cookie этого браузера и сохранённого хеша; общий итог за всё время остаётся. Если удалить их не удалось, сайт повторит запрос при следующей загрузке страницы, а счётчик останется отключённым.',
      'Google Analytics, Яндекс.Метрика, Яндекс.Вебвизор и Microsoft Clarity тоже запускаются по умолчанию, до какого-либо выбора посетителя. Эти сервисы могут получать адреса страниц, сведения о браузере и устройстве, примерное местоположение, клики, прокрутку, данные сеансов, cookies и похожие идентификаторы. Вебвизор и Clarity могут воспроизводить действия на странице. Провайдеры могут обрабатывать данные за пределами вашей страны по своим правилам. Каждый сервис можно отключить в настройках конфиденциальности, а кнопка «Отменить всё» отключает всё необязательное.',
      'Кнопка настроек конфиденциальности находится на этой странице. «Настроить» открывает отдельные переключатели с текущим выбором; «Сохранить выбор» применяет изменения. «Принять всё» включает все сервисы. Крестик только закрывает панель без изменения выбора. Выбор и его дата сохраняются в localStorage и в собственной служебной cookie advs_privacy_choice на срок до 395 дней. Эта cookie содержит только настройки и время сохранения, но не идентификатор посетителя. Изменение применяется, только если его удалось сохранить хотя бы в одном из этих мест; иначе продолжают действовать предыдущие настройки. Если сохранённого выбора нет, все необязательные сервисы включены. Выбранные язык и тема тоже сохраняются локально. Отключение аналитики прекращает её загрузку после перезагрузки страницы; ранее переданные данные остаются у провайдеров по их правилам, а уже созданные ими cookies могут сохраняться до удаления в браузере. По вопросам конфиденциальности и данным воспользуйтесь контактными ссылками на сайте.',
      'Шрифты загружаются с самого сайта, а не с серверов Google. Сейчас игры не сохраняют личные рекорды между посещениями. Если такая функция появится, до её включения будут описаны правила хранения и публикации результатов.',
    ],
  },
};
