import { createAdditionalTranslation } from './createAdditionalTranslation.js';

// Translation draft; native-speaker review is recommended.
export const ltTranslation = createAdditionalTranslation('lt', {
  nav: ['Apie mane', 'Patirtis', 'Žaidimai', 'Kontaktai'],
  labels: {
    navigation: 'Pagrindinė navigacija', mobileNavigation: 'Mobilioji navigacija', openMenu: 'Atverti meniu', closeMenu: 'Užverti meniu', theme: 'Tema', system: 'Sistemos', language: 'Kalba', signInInfo: 'Prisijungimo informacija', underDevelopment: 'Ši funkcija dar kuriama', profile: 'Profilis', social: 'Socialinių tinklų nuorodos', summary: 'Profesinė santrauka', cv: 'Gyvenimo aprašymas', work: 'Darbo patirtis', education: 'Išsilavinimas ir kursai', skills: 'Įgūdžiai ir įrankiai', cvEn: 'Atverti CV anglų kalba (PDF)', cvRu: 'Atverti CV rusų kalba (PDF)', stack: 'Technologijos', gameBoard: 'Žaidimo lenta', score: 'Taškai', gameOver: 'Žaidimas baigtas.', restart: 'Pradėti iš naujo', counter: 'Apsilankymų skaitiklis', personalSite: 'Asmeninė nekomercinė svetainė.', details: 'Daugiau informacijos:', environments: 'Aplinkos',
  },
  greeting: 'Sveiki visi!',
  summary: ['Sveiki atvykę į mano asmeninę darbų pristatymo svetainę.', 'Esu Full Stack QA Engineer, besispecializuojantis rankiniame ir automatizuotame naudotojo sąsajos, serverio dalies, žiniatinklio ir mobiliųjų programėlių testavime. Čia rasite mano CV, informaciją apie darbo patirtį, išsilavinimą, baigtus kursus ir kontaktus.', 'Taip pat galite žaisti naršyklinius žaidimus, kuriuos kuriu laisvalaikiu kaip techninius eksperimentus. Tikiuosi, jums patiks ši svetainė.'],
  about: ['Turiu inžinerinį išsilavinimą. Baigiau Maskvos valstybinį Baumano technikos universitetą, kur studijavau elektroninių įrenginių projektavimą ir programavimą.', 'Prieš pereidamas į IT dirbau keliose inžinerijos srityse, įskaitant bepiločių orlaivių sistemas ir pramoninę įrangą. Kai kuriuose projektuose koordinavau komandos darbą ir buvau atsakingas už techninius bei organizacinius klausimus.', 'Dabar dirbu QA inžinieriumi ir toliau tobulinu testavimo automatizavimo bei programavimo įgūdžius. Man svarbu ne tik rasti klaidas, bet ir suprasti visą sistemą: sąsają, API, integracijas ir infrastruktūrą. Testavimas turi iš tiesų gerinti produkto kokybę ir naudojimo patogumą, o ne būti formalumas.', 'Mokau ir konsultuoju pradedančius QA specialistus. Vertinu aiškų bendravimą, motyvaciją ir atsakingą požiūrį į darbą.', 'Laisvalaikiu mėgstu laisvąjį nardymą, žygius, buriavimą ir treniruotes su savo kūno svoriu. Taip pat mėgstu keliauti ir pažinti įvairias šalis.'],
  work: [{ period: '2024 m. rugpjūtis – dabar', before: 'Pardavėjų siuntų valdymo platformos ', after: ' kūrimas.' }, { period: '2022 m. gegužė – 2024 m. rugpjūtis', before: 'VTB banko grynųjų pinigų logistikos projektas, kurį vykdė ', after: ', skirtas inkasavimui automatizuoti ir bankomatų priežiūrai prognozuoti.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – dabar | Anglų kalbos kursai | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Maskvos valstybinis Baumano technikos universitetas | Radiotechnikos fakultetas | Radioelektroninių įrenginių projektavimas ir gamybos technologija | Pažymių vidurkis: 4,05.'],
  skillTitles: ['Testavimas', 'Automatizavimas ir IDE', 'API ir duomenys', 'Infrastruktūra ir žurnalai', 'Mobilieji įrenginiai ir naršyklių suderinamumas', 'Produktas ir procesai'],
  life: {
    description: ['Game of Life – ląstelinis automatas, kurį 1970 m. sukūrė matematikas John Conway. Tai žaidimas be žaidėjų: jo raidą lemia pradinė būsena, daugiau veiksmų nereikia. Lentą sudaro gyvų arba negyvų ląstelių tinklelis.', 'Raida vyksta pagal paprastas taisykles:'],
    rules: ['Gyva ląstelė, turinti mažiau nei dvi gyvas kaimynes, miršta dėl vienatvės.', 'Gyva ląstelė, turinti dvi ar tris gyvas kaimynes, išgyvena kitą kartą.', 'Gyva ląstelė, turinti daugiau nei tris gyvas kaimynes, miršta dėl perpildymo.', 'Negyva ląstelė, turinti lygiai tris gyvas kaimynes, atgyja.'],
    interaction: 'Spustelėkite ląsteles, kad pakeistumėte jų būseną. Išbandykite įvairius pradinius raštus ir stebėkite jų raidą.', controls: ['Eilutės', 'Stulpeliai', 'Ciklo trukmė (sek.)'], cycle: 'Ciklas', repeatingState: 'Žaidimas baigtas. Būsena kartojasi.', allCellsDead: 'Žaidimas baigtas. Visos ląstelės mirė.', toggleCell: 'Keisti ląstelės būseną',
  },
  contactMessage: 'Jei turite klausimų, susisiekite el. paštu arba socialiniuose tinkluose.', periods: ['Šiandien', '1 savaitė', '1 mėnuo', '1 metai', 'Iš viso'],
  privacy: { title: 'Privatumas ir teisinė informacija', lastUpdated: 'Atnaujinta: 2026 m. rugpjūčio 20 d.', sections: [
    { title: 'Nekomercinė paskirtis', paragraphs: ['Ši asmeninė svetainė skirta mokymuisi, darbų pristatymui, pramogoms ir asmeniniam bendravimui. Tai nėra parduotuvė, prekyvietė, mokama paslauga, lošimų ar finansinių paslaugų svetainė arba profesionalių teisinių, medicininių ar finansinių konsultacijų platforma.', 'Svetainė neskirta tiesiogiai uždirbti iš lankytojų, parduoti jų duomenis ar apmokestinti prieigą prie naršyklinių žaidimų, straipsnių, puslapių ir eksperimentų.'] },
    { title: 'Asmeninis naudojimas ir mokymasis', paragraphs: ['Tai asmeninis mokymosi ir darbų pristatymo projektas. Kodas, sąsajos eksperimentai, žaidimai ir viešas turinys gali demonstruoti sąsajų kūrimo, QA, testavimo, automatizavimo, dizaino ir inžinerijos įgūdžius.', 'Pavyzdžiai, žaidimų mechanikos, ekrano vaizdai, nuorodos ir pavadinimai naudojami tik aiškinimui, mokymuisi, testavimui arba įprastų žiniatinklio kūrimo idėjų demonstravimui.'] },
    { title: 'Nėra mokamų paslaugų ar prekybos', paragraphs: ['Svetainė neapdoroja mokėjimų, nerenka atsiskaitymo duomenų ir neparduoda prenumeratų ar skaitmeninių prekių. Prieš ateityje paskelbiant komercines funkcijas, ši politika turi būti atnaujinta.'] },
    { title: 'Lankytojų, paskyrų ir kontaktiniai duomenys', paragraphs: ['Svetainėje yra arba gali būti registracijos ir prisijungimo funkcijų. Gali būti renkami vardas, slapyvardis, el. paštas ir slaptažodis. Sąmoningai neprašoma mokėjimo duomenų, tapatybės dokumentų ar jautrių asmens duomenų.', 'Registruotiems naudotojams nesiunčiamas šlamštas, rinkodaros naujienlaiškiai ar nesusijusi reklama. El. paštas naudojamas tik paskyros klausimams, slaptažodžio atkūrimo pagalbai, tiesioginiams atsakymams ir būtiniems techniniams pranešimams.', 'Nenaudokite to paties slaptažodžio kitose svetainėse, programėlėse, el. pašte, bankuose, socialiniuose tinkluose ar darbo sistemose. Savininkas neatsako už žalą dėl pakartotinai naudojamo slaptažodžio, kuris nutekėjo, buvo atspėtas, pavogtas ar pažeistas kitur.', 'Automatinis slaptažodžio atkūrimas gali būti nepasiekiamas. Prireikus rašykite antondorovs@gmail.com ir pateikite pakankamai paskyros informacijos užklausai nustatyti.', 'Susisiekiant per išorines nuorodas, socialinius tinklus, žinučių ar el. pašto paslaugas, duomenis tvarko pasirinktas teikėjas pagal savo sąlygas ir privatumo politiką.'] },
    { title: 'Analitika ir trečiųjų šalių paslaugos', paragraphs: ['Google Analytics, Yandex Metrica ir Microsoft Clarity padeda suprasti srautą, našumą, klaidas ir sąveiką. Jie gali tvarkyti puslapių adresus, apytikrę vietą pagal tinklo duomenis, naršyklės ir įrenginio informaciją, seansus, slapukus ar panašius identifikatorius, paspaudimus, slinkimą ir kitą sąveiką.', 'Analitika naudojama kokybei, patogumui, stabilumui ir turiniui gerinti, o ne lankytojams pagal vardą nustatyti, asmeniniams profiliams parduoti ar mokamai tikslinei reklamai teikti.', 'Vidinis puslapių įkėlimų skaitiklis saugo paskutinių 365 dienų bendrus dienos duomenis pagal UTC ir atskirą viso laikotarpio sumą. Jis nesaugo IP adresų, vardų, el. pašto, naršyklės duomenų, slapukų, įrenginių identifikatorių ar individualios lankymo istorijos.', 'Google, Yandex ir Microsoft duomenis tvarko pagal savo sąlygas, privatumo politiką ir techninius nustatymus. Galite naudoti naršyklės privatumo funkcijas, turinio blokavimą, slapukų nustatymus ir teikėjų atsisakymo priemones, jei jos prieinamos.'] },
    { title: 'Slapukai ir vietinė saugykla', paragraphs: ['Svetainė gali saugoti sąsajos nuostatas naršyklėje. Pasirinkta tema ir kalba išsaugomos localStorage tarp apsilankymų.', 'Skaitiklis gali didėti po kiekvieno pilno puslapio įkėlimo, įskaitant atnaujinimą. Laikotarpiai yra slenkantys langai iki dabartinės UTC datos, o ne kalendorinės savaitės, mėnesiai ar metai. Individualūs lankytojai neatpažįstami ir pasikartojantys apsilankymai nepašalinami.', 'Trečiųjų šalių analitika gali naudoti slapukus ir panašias technologijas. Veikimas priklauso nuo naršyklės, regiono, privatumo nustatymų ir dabartinės teikėjo konfigūracijos.'] },
    { title: 'Žaidimų projektai ir trečiųjų šalių teisės', paragraphs: ['Naršykliniai žaidimai yra asmeniniai mokymosi projektai, įkvėpti įprastų žiniatinklio žaidimų mechanikų ir arkadinių koncepcijų. Tai nėra oficialios versijos, licencijuotos adaptacijos, komerciniai perdirbiniai ar originalų pakaitalai.', 'Svetainė nepretenduoja į kitų veikėjus, prekių ženklus, žaidimų pavadinimus, koncepcijas, garsus, vaizdo stilius ar originalią medžiagą. Gavus pagrįstą prašymą, galimai teises pažeidžianti medžiaga bus peržiūrėta ir pašalinta arba pakeista.'] },
    { title: 'Prekių ženklai, pavadinimai ir autorių teisės', paragraphs: ['Minimi ženklai, įmonių, produktų ir paslaugų pavadinimai, logotipai ir saugomi kūriniai priklauso jų savininkams. Paminėjimas nereiškia pritarimo, rėmimo, partnerystės ar ryšio, jei tai aiškiai nenurodyta.', 'Originalūs tekstai, kodas, maketai ir asmeninė medžiaga skelbiami darbų pristatymo ir mokymosi tikslais. Nekopijuokite jų į komercinius produktus be leidimo.'] },
    { title: 'Išorinės nuorodos', paragraphs: ['Svetainėje gali būti nuorodų į išorines svetaines, socialinius tinklus, kodų saugyklas, žinučių paslaugas, kūrimo įrankius, analitikos teikėjus ir projektų aplinkas. Juos valdo atitinkami savininkai ir jie gali rinkti duomenis pagal savo politiką.', 'Savininkas neatsako už išorinį turinį, privatumo praktiką ar trečiųjų šalių paslaugų prieinamumą.'] },
    { title: 'Kontaktai', paragraphs: ['Klausimams apie svetainę, privatumą, teisinę informaciją, turinio pašalinimą ar teises naudokite pagrindinio puslapio kontaktines nuorodas. Pateikite pakankamai informacijos puslapiui, medžiagai ar problemai nustatyti.'] },
  ] },
});
