import { createAdditionalTranslation } from './createAdditionalTranslation.js';

// Translation draft; native-speaker review is recommended.
export const filTranslation = createAdditionalTranslation('fil', {
  nav: ['Tungkol sa akin', 'Karanasan', 'Mga laro', 'Kontak'],
  labels: { navigation: 'Pangunahing nabigasyon', mobileNavigation: 'Nabigasyon sa mobile', openMenu: 'Buksan ang menu', closeMenu: 'Isara ang menu', theme: 'Tema', system: 'Sistema', language: 'Wika', signInInfo: 'Impormasyon sa pag-sign in', underDevelopment: 'Ginagawa pa ang feature na ito', profile: 'Profile', social: 'Mga link sa social media', summary: 'Buod ng propesyonal na karanasan', cv: 'CV', work: 'Karanasan sa trabaho', education: 'Edukasyon at mga kurso', skills: 'Mga kasanayan at tool', cvEn: 'Buksan ang CV sa Ingles (PDF)', cvRu: 'Buksan ang CV sa Ruso (PDF)', stack: 'Mga teknolohiya', gameBoard: 'Lugar ng laro', score: 'Puntos', gameOver: 'Tapos na ang laro.', restart: 'Magsimula muli', counter: 'Bilang ng mga pagbisita', personalSite: 'Personal at di-komersiyal na website.', details: 'Para sa higit pang impormasyon:', environments: 'Mga environment' },
  greeting: 'Kumusta sa lahat!',
  summary: ['Maligayang pagdating sa aking personal na portfolio website.', 'Isa akong Full Stack QA Engineer na dalubhasa sa manual at automated testing ng frontend, backend, web, at mobile application. Dito makikita ang aking CV, karanasan sa trabaho, edukasyon, mga natapos na kurso, at detalye sa pakikipag-ugnayan.', 'Maaari ka ring maglaro ng mga browser game na ginagawa ko sa libreng oras bilang mga teknikal na eksperimento. Sana ay magustuhan mo ang website.'],
  about: ['May background ako sa engineering. Nagtapos ako sa Bauman Moscow State Technical University, na nakatuon sa disenyo at programming ng mga elektronikong aparato.', 'Bago lumipat sa IT, nagtrabaho ako sa ilang larangan ng engineering, kabilang ang mga sistema ng sasakyang panghimpapawid na walang piloto at kagamitang pang-industriya. Sa ilang proyekto, nag-ugnay rin ako ng gawain ng team at humawak ng mga teknikal at pang-organisasyong responsibilidad.', 'Nagtatrabaho ako ngayon bilang QA engineer at patuloy na pinauunlad ang aking kasanayan sa test automation at programming. Mahalaga sa akin hindi lang ang pagtuklas ng bug kundi ang pag-unawa sa buong sistema: UI, API, mga integration, at infrastructure. Dapat talagang mapabuti ng testing ang kalidad at kadalian ng paggamit ng produkto, hindi maging pormalidad lamang.', 'Nagtuturo at gumagabay ako sa mga nagsisimulang QA specialist. Pinahahalagahan ko ang malinaw na komunikasyon, motibasyon, at pananagutan sa trabaho.', 'Sa libreng oras, mahilig ako sa freediving, hiking, paglalayag, at calisthenics. Mahilig din akong maglakbay at bumisita sa iba’t ibang bansa.'],
  work: [{ period: 'Ago. 2024 – kasalukuyan', before: 'Pagbuo ng platform para sa mga nagbebenta na ', after: ' para sa pamamahala ng mga pakete.' }, { period: 'Mayo 2022 – Ago. 2024', before: 'Proyekto ng cash logistics ng VTB Bank mula sa ', after: ' para awtomatikong pamahalaan ang koleksiyon ng pera at hulaan ang pangangailangan sa pagseserbisyo ng ATM.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – kasalukuyan | Mga kurso sa Ingles | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Bauman Moscow State Technical University | Faculty ng Radio Engineering | Disenyo at teknolohiya ng paggawa ng mga radioelectronic na aparato | Karaniwang marka: 4.05.'],
  skillTitles: ['Testing', 'Automation at IDE', 'API at data', 'Infrastructure at mga log', 'Mobile at cross-browser', 'Produkto at mga proseso'],
  life: { description: ['Ang Game of Life ay isang cellular automaton na ginawa ng matematikong si John Conway noong 1970. Wala itong manlalaro: ang paunang estado ang nagtatakda ng pag-unlad nito nang walang karagdagang input. Binubuo ang board ng grid ng mga cell na buhay o patay.', 'Sinusunod nito ang mga simpleng tuntunin:'], rules: ['Namamatay ang buhay na cell na may mas kaunti sa dalawang buhay na kapitbahay dahil sa kakulangan ng populasyon.', 'Nabubuhay hanggang sa susunod na henerasyon ang buhay na cell na may dalawa o tatlong buhay na kapitbahay.', 'Namamatay ang buhay na cell na may higit sa tatlong buhay na kapitbahay dahil sa sobrang populasyon.', 'Nagiging buhay ang patay na cell na may eksaktong tatlong buhay na kapitbahay.'], interaction: 'I-click ang mga cell upang baguhin ang kanilang estado. Subukan ang iba’t ibang paunang pattern at tingnan ang pag-unlad ng mga ito.', controls: ['Mga hilera', 'Mga hanay', 'Tagal ng siklo (seg.)'], cycle: 'Siklo', repeatingState: 'Tapos na ang laro. Naulit ang isang estado.', allCellsDead: 'Tapos na ang laro. Patay na ang lahat ng cell.', toggleCell: 'Baguhin ang estado ng cell' },
  contactMessage: 'Kung may tanong ka, makipag-ugnayan sa akin sa email o social media.', periods: ['Ngayon', '1 linggo', '1 buwan', '1 taon', 'Kabuuan'],
  privacy: { title: 'Privacy at legal na impormasyon', lastUpdated: 'Huling na-update: Agosto 20, 2026', sections: [
    { title: 'Di-komersiyal na layunin', paragraphs: ['Ang personal na website na ito ay para sa pag-aaral, portfolio, libangan, at personal na komunikasyon. Hindi ito tindahan, marketplace, bayad na serbisyo, sugal, serbisyong pinansiyal, o platform para sa propesyonal na payong legal, medikal, o pinansiyal.', 'Hindi layunin ng site na direktang kumita mula sa mga bisita, ibenta ang kanilang data, o maningil para sa access sa mga browser game, artikulo, pahina, o eksperimento.'] },
    { title: 'Personal na paggamit at pag-aaral', paragraphs: ['Ito ay personal na proyekto sa pag-aaral at portfolio. Maaaring ipakita ng code, mga eksperimento sa interface, browser game, at pampublikong nilalaman ang mga kasanayan sa frontend, QA, testing, automation, design, at engineering.', 'Ginagamit lamang ang mga halimbawa, mekanika ng laro, screenshot, sanggunian, at pangalan para sa pagpapaliwanag, pag-aaral, testing, o pagpapakita ng mga karaniwang ideya sa web development.'] },
    { title: 'Walang bayad na serbisyo o bentahan', paragraphs: ['Hindi nagpoproseso ng bayad, nangongolekta ng billing data, o nagbebenta ng subscription o digital na produkto ang site. Kailangang baguhin muna ang patakarang ito bago ilunsad ang anumang komersiyal na feature sa hinaharap.'] },
    { title: 'Data ng bisita, account, at kontak', paragraphs: ['Mayroon o maaaring magkaroon ng registration at sign-in ang site. Maaaring kasama sa registration ang pangalan, palayaw, email, at password. Hindi sadyang hinihingi ang payment data, dokumento ng pagkakakilanlan, o sensitibong personal na data.', 'Hindi padadalhan ang mga rehistradong user ng spam, marketing newsletter, o hindi kaugnay na promosyon. Ginagamit lang ang email para sa account, tulong sa password, direktang sagot, o kinakailangang teknikal na abiso.', 'Huwag gamitin muli ang password ng ibang website, app, email, bangko, social network, o sistema sa trabaho. Hindi pananagutan ng may-ari ang pinsala mula sa muling paggamit ng password na na-leak, nahulaan, ninakaw, o nakompromiso sa ibang lugar.', 'Maaaring walang awtomatikong pagbawi ng password. Kung kailangan, sumulat sa antondorovs@gmail.com at magbigay ng sapat na impormasyon ng account upang matukoy ang kahilingan.', 'Kung makikipag-ugnayan sa pamamagitan ng mga panlabas na link, social platform, messaging service, o email client, ipoproseso ng napiling serbisyo ang data ayon sa sarili nitong tuntunin at patakaran sa privacy.'] },
    { title: 'Analytics at mga third-party na serbisyo', paragraphs: ['Ginagamit ang Google Analytics, Yandex Metrica, at Microsoft Clarity upang maunawaan ang traffic, performance, error, at interaksiyon. Maaari nilang iproseso ang URL, tinatayang lokasyon mula sa network, browser at device, session, cookie o katulad na identifier, click, scroll, at iba pang interaksiyon.', 'Ginagamit ang analytics para mapabuti ang kalidad, kadalian ng paggamit, katatagan, at nilalaman, hindi para kilalanin ang bisita sa pangalan, ibenta ang personal na profile, o magbigay ng bayad na targeted advertising.', 'Ang panloob na bilang ng page load ay nag-iimbak ng pinagsama-samang arawang bilang sa UTC para sa huling 365 araw at hiwalay na kabuuang bilang. Hindi ito nag-iimbak ng IP address, pangalan, email, browser data, cookie, device identifier, o indibidwal na kasaysayan ng pagbisita.', 'Nagpoproseso ang Google, Yandex, at Microsoft ayon sa sarili nilang tuntunin, privacy policy, at teknikal na setting. Maaari mong gamitin ang privacy setting ng browser, content blocker, cookie control, o opt-out tool ng provider kung mayroon.'] },
    { title: 'Cookies at lokal na storage', paragraphs: ['Maaaring gamitin ng site ang storage ng browser para sa mga setting ng interface. Nananatili sa localStorage ang napiling tema at wika sa pagitan ng mga pagbisita.', 'Maaaring tumaas ang bilang sa bawat buong pag-load ng pahina, kasama ang refresh. Ang mga panahon ay gumagalaw na saklaw hanggang sa kasalukuyang petsa sa UTC, hindi mga linggo, buwan, o taon sa kalendaryo. Hindi nito kinikilala ang bawat bisita o inaalis ang mga paulit-ulit na pagbisita.', 'Maaaring gumamit ng cookies at katulad na teknolohiya ang third-party analytics. Nakadepende ito sa browser, rehiyon, privacy setting, at kasalukuyang configuration ng provider.'] },
    { title: 'Mga larong proyekto at karapatan ng iba', paragraphs: ['Ang mga browser game ay personal na proyekto sa pag-aaral na inspirasyon ang mga karaniwang mekanika ng web game at konsepto ng arcade. Hindi sila opisyal na bersiyon, lisensiyadong port, komersiyal na remake, o kapalit ng orihinal.', 'Hindi inaangkin ng site ang mga karakter, brand, pamagat ng laro, trademark, konsepto, tunog, visual style, o orihinal na asset ng iba. Susuriin at aalisin o papalitan ang materyal na maaaring lumabag sa lehitimong karapatan kapag may makatwirang kahilingan.'] },
    { title: 'Mga trademark, pangalan, at copyright', paragraphs: ['Ang mga nabanggit na trademark, pangalan ng kumpanya, produkto at serbisyo, logo, at gawang may copyright ay pag-aari ng kani-kanilang may-ari. Hindi nangangahulugan ang pagbanggit ng pag-endorso, sponsorship, partnership, o affiliation maliban kung malinaw na nakasaad.', 'Inilalathala ang orihinal na teksto, code, layout, at personal na materyal para sa portfolio at pag-aaral. Huwag kopyahin ang mga ito sa komersiyal na produkto nang walang pahintulot.'] },
    { title: 'Mga panlabas na link', paragraphs: ['Maaaring mag-link ang site sa ibang website, social network, code repository, messaging service, development tool, analytics provider, at project environment. Pinamamahalaan ang mga ito ng sarili nilang may-ari at maaari silang mangolekta ng data ayon sa sarili nilang patakaran.', 'Hindi pananagutan ng may-ari ang panlabas na nilalaman, privacy practice, o availability ng third-party na serbisyo.'] },
    { title: 'Kontak', paragraphs: ['Para sa mga tanong tungkol sa site, privacy, legal na impormasyon, pag-alis ng nilalaman, o mga karapatan, gamitin ang mga contact link sa home page. Magbigay ng sapat na detalye upang matukoy ang pahina, materyal, o problema.'] },
  ] },
});
