import { createAdditionalTranslation } from './createAdditionalTranslation.js';

export const nbTranslation = createAdditionalTranslation('nb', {
  nav: ['Om meg', 'Erfaring', 'Spill', 'Kontakt'],
  labels: { navigation: 'Hovednavigasjon', mobileNavigation: 'Mobilnavigasjon', openMenu: 'Åpne menyen', closeMenu: 'Lukk menyen', theme: 'Tema', system: 'System', language: 'Språk', signInInfo: 'Informasjon om innlogging', underDevelopment: 'Denne funksjonen er under utvikling', profile: 'Profil', social: 'Lenker til sosiale medier', summary: 'Faglig sammendrag', cv: 'CV', work: 'Arbeidserfaring', education: 'Utdanning og kurs', skills: 'Ferdigheter og verktøy', cvEn: 'Åpne CV på engelsk (PDF)', cvRu: 'Åpne CV på russisk (PDF)', stack: 'Teknologier', gameBoard: 'Spillebrett', score: 'Poeng', gameOver: 'Spillet er over.', restart: 'Start på nytt', counter: 'Besøksteller', personalSite: 'Personlig, ikke-kommersielt nettsted.', details: 'Les mer:', environments: 'Miljøer' },
  greeting: 'Hei alle sammen!',
  summary: ['Velkommen til mitt personlige porteføljenettsted.', 'Jeg er Full Stack QA Engineer med spesialisering i manuell og automatisert testing av frontend, backend, nett- og mobilapplikasjoner. Her finner du CV-en min, informasjon om arbeidserfaring, utdanning og fullførte kurs samt kontaktopplysningene mine.', 'Du kan også spille nettleserspill som jeg lager på fritiden som en del av mine tekniske eksperimenter. Jeg håper du liker nettstedet.'],
  about: ['Jeg har ingeniørbakgrunn. Jeg ble uteksaminert fra Bauman statlige tekniske universitet i Moskva med en utdanning rettet mot konstruksjon og programmering av elektroniske enheter.', 'Før jeg gikk over til IT, jobbet jeg innen flere ingeniørfag, blant annet ubemannede luftfartssystemer og industriutstyr. I enkelte prosjekter koordinerte jeg også teamets arbeid og hadde ansvar for tekniske og organisatoriske oppgaver.', 'Jeg jobber nå som QA-ingeniør og videreutvikler ferdighetene mine innen testautomatisering og programmering. Jeg vil ikke bare finne feil, men også forstå hele systemet, fra brukergrensesnitt og API til integrasjoner og infrastruktur. Testing bør etter mitt syn forbedre kvalitet og brukervennlighet i praksis, ikke bare være en formalitet.', 'Jeg lærer opp og veileder nye QA-spesialister. Jeg har gode kommunikasjonsevner, sterk motivasjon og en ansvarsbevisst tilnærming.', 'På fritiden liker jeg fridykking, fotturer, seiling og kroppsvekttrening. Jeg er også glad i å reise og besøke ulike land.'],
  work: [{ period: 'Aug. 2024 – nå', before: 'Utvikling av selgerplattformen ', after: ' for pakkehåndtering.' }, { period: 'Mai 2022 – aug. 2024', before: 'VTB Banks kontantlogistikkprosjekt fra ', after: ' for automatisering av kontantinnsamling og prognoser for vedlikehold av minibanker.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – nå | Engelskkurs | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Bauman statlige tekniske universitet i Moskva | Fakultet for radioteknikk | Konstruksjon og produksjonsteknologi for radioelektroniske enheter | Karaktersnitt: 4,05.'],
  skillTitles: ['Testing', 'Automatisering og IDE', 'API og data', 'Infrastruktur og logger', 'Mobil og nettleserkompatibilitet', 'Produkt og prosesser'],
  life: { description: ['Game of Life er en cellulær automat utviklet av matematikeren John Conway i 1970. Det er et spill uten spillere: utviklingen bestemmes av starttilstanden uten flere inngrep. Brettet er et rutenett med celler som enten er levende eller døde.', 'Utviklingen følger enkle regler:'], rules: ['En levende celle med færre enn to levende naboer dør av underbefolkning.', 'En levende celle med to eller tre levende naboer lever videre til neste generasjon.', 'En levende celle med flere enn tre levende naboer dør av overbefolkning.', 'En død celle med nøyaktig tre levende naboer blir levende.'], interaction: 'Klikk på cellene for å endre tilstanden deres. Prøv ulike startmønstre og se hvordan de utvikler seg over tid.', controls: ['Rader', 'Kolonner', 'Syklustid (sek.)'], cycle: 'Syklus', repeatingState: 'Spillet er over. En tidligere tilstand gjentar seg.', allCellsDead: 'Spillet er over. Alle cellene er døde.', toggleCell: 'Endre cellens tilstand' },
  contactMessage: 'Har du spørsmål, kan du kontakte meg via e-post eller sosiale medier.', periods: ['I dag', '1 uke', '1 måned', '1 år', 'Totalt'],
  privacy: { title: 'Personvern og juridisk informasjon', lastUpdated: 'Sist oppdatert: 20. august 2026', sections: [
    { title: 'Ikke-kommersielt formål', paragraphs: ['Dette personlige nettstedet drives for læring, portefølje, underholdning og personlig kommunikasjon. Det er ikke en nettbutikk, markedsplass, betalt tjeneste, pengespilltjeneste, finansiell tjeneste eller plattform for profesjonelle juridiske, medisinske eller økonomiske råd.', 'Formålet er ikke å tjene direkte på besøkende, selge opplysningene deres eller ta betalt for tilgang til nettleserspill, artikler, sider eller eksperimenter.'] },
    { title: 'Personlig bruk og læring', paragraphs: ['Nettstedet er et personlig læringsprosjekt og en portefølje. Kode, grensesnitteksperimenter, nettleserspill og offentlig innhold kan vise ferdigheter innen frontend, QA, testing, automatisering, design og ingeniørfag.', 'Eksempler, spillmekanikker, skjermbilder, henvisninger og navn brukes bare til å forklare, lære, teste eller demonstrere vanlige ideer innen nettutvikling.'] },
    { title: 'Ingen betalte tjenester eller salg', paragraphs: ['Nettstedet behandler ikke betalinger, samler ikke inn faktureringsopplysninger og selger verken abonnementer eller digitale varer. Eventuelle kommersielle funksjoner krever at denne erklæringen oppdateres før de lanseres.'] },
    { title: 'Besøks-, konto- og kontaktopplysninger', paragraphs: ['Nettstedet har eller kan få registrering og innlogging. Registreringsdata kan omfatte navn, kallenavn, e-postadresse og passord. Det bes ikke bevisst om betalingsopplysninger, identitetsdokumenter eller sensitive personopplysninger i registreringen.', 'Registrerte brukere får ikke søppelpost, markedsføringsnyhetsbrev eller uvedkommende reklame. E-post brukes bare til kontorelaterte henvendelser, hjelp med passordgjenoppretting, direkte svar eller nødvendige tekniske varsler.', 'Ikke gjenbruk passord fra andre nettsteder, apper, e-postkontoer, banker, sosiale nettverk eller arbeidssystemer. Eieren er ikke ansvarlig for skade fra gjenbruk av passord som senere lekkes, gjettes, stjeles eller kompromitteres andre steder.', 'Automatisk passordgjenoppretting er ikke alltid tilgjengelig. Ved behov kan du skrive til antondorovs@gmail.com med nok kontoinformasjon til å identifisere forespørselen.', 'Ved kontakt gjennom eksterne lenker, sosiale plattformer, meldingstjenester eller e-postprogrammer behandles data av den valgte tjenesten etter dens egne vilkår og personvernregler.'] },
    { title: 'Analyse og tredjepartstjenester', paragraphs: ['Google Analytics, Yandex Metrica og Microsoft Clarity brukes til å forstå trafikk, ytelse, feil og brukersamhandling. De kan behandle sideadresser, omtrentlig posisjon utledet fra nettverksdata, nettleser- og enhetsinformasjon, økter, informasjonskapsler eller lignende identifikatorer, klikk, rulling og annen samhandling.', 'Analysedata brukes til å forbedre kvalitet, brukervennlighet, stabilitet og innhold, ikke til å identifisere besøkende ved navn, selge personprofiler eller tilby betalt målrettet reklame.', 'Den interne sidetelleren lagrer samlede dagstall i UTC for de siste 365 dagene og et separat totaltall. Den lagrer ikke IP-adresser, navn, e-postadresser, nettleserdetaljer, informasjonskapsler, enhetsidentifikatorer eller individuelle besøkshistorikker.', 'Google, Yandex og Microsoft behandler opplysninger etter egne vilkår, personvernregler og tekniske innstillinger. Bruk nettleserens personverninnstillinger, innholdsblokkering, kontroll av informasjonskapsler eller leverandørenes reservasjonsverktøy der de finnes.'] },
    { title: 'Informasjonskapsler og lokal lagring', paragraphs: ['Nettstedet kan bruke nettleserlagring til grensesnittinnstillinger. Valgt tema og språk lagres i localStorage mellom besøk.', 'Telleren kan øke ved hver fullstendige sideinnlasting, også ved oppdatering. Periodene er rullerende tidsvinduer frem til gjeldende UTC-dato, ikke kalenderuker, -måneder eller -år. Den identifiserer eller dedupliserer ikke enkeltbesøkende.', 'Eksterne analyseverktøy kan bruke informasjonskapsler og lignende teknologier. Virkemåten avhenger av nettleser, region, personvernvalg og leverandørenes aktuelle oppsett.'] },
    { title: 'Spillprosjekter og andres rettigheter', paragraphs: ['Nettleserspillene er personlige læringsprosjekter inspirert av vanlige nettspillmekanikker og kjente arkadekonsepter. De er ikke offisielle versjoner, lisensierte tilpasninger, kommersielle nyutgaver eller erstatninger for originalene.', 'Nettstedet gjør ikke krav på andres figurer, merker, spilltitler, varemerker, konsepter, lyder, visuelle stiler eller originalmateriale. Materiale som kan stride mot legitime rettigheter, vil bli vurdert og fjernet eller erstattet etter en rimelig henvendelse.'] },
    { title: 'Varemerker, navn og opphavsrett', paragraphs: ['Omtalte varemerker, firma-, produkt- og tjenestenavn, logoer og opphavsrettslig beskyttede verk tilhører sine respektive eiere. Omtale innebærer ikke godkjenning, sponsing, partnerskap eller tilknytning med mindre det uttrykkelig er oppgitt.', 'Original tekst, kode, layout og personlig materiale publiseres for portefølje- og læringsformål. De må ikke kopieres til kommersielle produkter uten tillatelse.'] },
    { title: 'Eksterne lenker', paragraphs: ['Nettstedet kan lenke til eksterne nettsteder, sosiale nettverk, kodearkiver, meldingstjenester, utviklingsverktøy, analyseleverandører og prosjektmiljøer. Disse styres av egne eiere og kan samle inn data etter egne regler.', 'Eieren er ikke ansvarlig for eksternt innhold, eksterne personvernpraksiser eller tilgjengeligheten til tredjepartstjenester.'] },
    { title: 'Kontakt', paragraphs: ['Bruk kontaktlenkene på forsiden ved spørsmål om nettstedet, personvern, juridisk informasjon, fjerning av innhold eller rettigheter. Ta med nok informasjon til å identifisere siden, materialet eller problemet.'] },
  ] },
});
