export const viTranslation = {
  nav: { home: 'Trang chủ', about: 'Giới thiệu', experience: 'Kinh nghiệm', games: 'Trò chơi', contacts: 'Liên hệ', signIn: 'Đăng nhập' },
  header: {
    primaryNavLabel: 'Điều hướng chính', mobileNavLabel: 'Điều hướng trên di động', menuButton: { open: 'Mở menu điều hướng', close: 'Đóng menu điều hướng' },
    theme: { buttonLabel: ({ selectedMode, effectiveTheme }) => `Đổi giao diện. Chế độ đã chọn: ${selectedMode}. Giao diện hiện tại: ${effectiveTheme}.`, menuLabel: 'Giao diện', menuTitle: 'Giao diện', modes: { auto: 'Hệ thống', dark: 'Tối', light: 'Sáng' } },
    language: { buttonLabel: ({ selectedLanguage }) => `Đổi ngôn ngữ. Ngôn ngữ đã chọn: ${selectedLanguage}.`, menuLabel: 'Ngôn ngữ', menuTitle: 'Ngôn ngữ' },
    signIn: { buttonLabel: 'Mở thông tin đăng nhập', menuLabel: 'Thông tin đăng nhập', menuTitle: 'Đăng nhập', message: 'Tính năng này đang được phát triển' },
  },
  homeBanner: { greeting: 'Xin chào mọi người!' },
  intro: { ariaLabel: 'Giới thiệu cá nhân', socialAriaLabel: 'Liên kết mạng xã hội', socialLabels: { telegram: 'Hồ sơ Telegram', linkedin: 'Hồ sơ LinkedIn', x: 'Hồ sơ X', github: 'Hồ sơ GitHub', gitlab: 'Hồ sơ GitLab' } },
  summary: { ariaLabel: 'Tóm tắt chuyên môn', lines: ['Chào mừng bạn đến với trang portfolio cá nhân của tôi.', 'Tôi là một Full Stack QA Engineer, chuyên kiểm thử thủ công và tự động cho các ứng dụng frontend, backend, web và di động. Tại đây, bạn có thể tìm thấy CV, thông tin về kinh nghiệm làm việc, học vấn, các khóa học đã hoàn thành và thông tin liên hệ của tôi.', 'Bạn cũng có thể chơi những trò chơi trên trình duyệt mà tôi tạo trong thời gian rảnh để thử nghiệm kỹ thuật. Hy vọng bạn sẽ thích trang web này.'] },
  about: { title: 'Giới thiệu', lines: [
    'Tôi có nền tảng kỹ thuật và đã tốt nghiệp Đại học Kỹ thuật Quốc gia Moskva Bauman, với chuyên ngành tập trung vào thiết kế và lập trình thiết bị điện tử.',
    'Trước khi chuyển sang CNTT, tôi làm việc trong một số lĩnh vực kỹ thuật, bao gồm hệ thống máy bay không người lái và thiết bị công nghiệp. Trong một số dự án, tôi còn điều phối công việc của nhóm và đảm nhận các nhiệm vụ kỹ thuật, tổ chức.',
    'Hiện tôi làm kỹ sư QA và tiếp tục phát triển kỹ năng tự động hóa kiểm thử và lập trình. Tôi không chỉ quan tâm đến việc tìm lỗi mà còn muốn hiểu cách toàn bộ hệ thống vận hành, từ giao diện và API đến các tích hợp và hạ tầng. Tôi cho rằng kiểm thử không nên chỉ là thủ tục, mà phải thực sự cải thiện chất lượng và tính dễ sử dụng của sản phẩm.',
    'Tôi đào tạo và hướng dẫn các chuyên viên QA mới. Tôi có kỹ năng giao tiếp tốt, động lực cao và tinh thần trách nhiệm.',
    'Trong thời gian rảnh, tôi thích lặn tự do, đi bộ đường dài, chèo thuyền buồm và tập thể dục với trọng lượng cơ thể. Tôi cũng thích du lịch và khám phá các quốc gia khác nhau.',
  ] },
  experience: {
    title: 'Kinh nghiệm', groups: { cv: 'CV', work: 'Kinh nghiệm làm việc', education: 'Học vấn và khóa học', skills: 'Kỹ năng và công cụ' }, cvLinks: { en: 'Mở CV tiếng Anh (PDF)', ru: 'Mở CV tiếng Nga (PDF)' }, techStack: 'Công nghệ sử dụng',
    work: [{ period: '08/2024 - hiện tại', before: 'Phát triển nền tảng dành cho người bán ', after: ' để quản lý bưu kiện.' }, { period: '05/2022 - 08/2024', before: 'Dự án logistics tiền mặt cho ngân hàng VTB của ', after: ', nhằm tự động hóa hoạt động vận chuyển tiền mặt và dự báo nhu cầu phục vụ máy ATM.' }],
    education: ['2024 - 2025 | Automation QA Engineer | Quality Academy.', '2023 - 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 - 2022 | Manual QA Engineer | Quality Academy.', '2020 - hiện tại | Các khóa tiếng Anh | SkyEng, Duolingo, LinguaTrip.', '2008 - 2015 | Đại học Kỹ thuật Quốc gia Moskva Bauman | Khoa Kỹ thuật vô tuyến | Thiết kế và công nghệ sản xuất thiết bị điện tử vô tuyến | Điểm trung bình: 4,05.'],
    skillTitles: ['Kiểm thử', 'Tự động hóa và IDE', 'API và dữ liệu', 'Hạ tầng và nhật ký', 'Di động và đa trình duyệt', 'Sản phẩm và quy trình'],
  },
  games: {
    sectionTitle: 'Trò chơi', placeholder: 'Mục này đang được phát triển...', snakeBoardLabel: 'Bàn chơi Snake', snakeUnlimitedBoardLabel: 'Bàn chơi Snake unlimited',
    dino: { ariaLabel: 'Trò chơi Dino', score: (score) => `Điểm: ${score}`, gameOver: (score) => `Kết thúc trò chơi. Điểm: ${score}.`, restart: 'Chơi lại' },
    life: { ariaLabel: 'Trò chơi sự sống', description: ['Game of Life là một hệ tự động tế bào do nhà toán học John Conway tạo ra năm 1970. Trò chơi không cần người chơi: diễn biến hoàn toàn do trạng thái ban đầu quyết định. Trò chơi diễn ra trên một lưới, trong đó mỗi ô ở trạng thái sống hoặc chết.', 'Sự biến đổi tuân theo các quy tắc đơn giản:'], rules: ['Ô sống có ít hơn hai ô láng giềng sống sẽ chết do cô lập.', 'Ô sống có hai hoặc ba ô láng giềng sống sẽ tồn tại sang thế hệ tiếp theo.', 'Ô sống có hơn ba ô láng giềng sống sẽ chết do quá đông.', 'Ô chết có đúng ba ô láng giềng sống sẽ trở thành ô sống.'], interaction: 'Nhấp vào các ô để đổi trạng thái. Hãy thử các cấu hình ban đầu khác nhau và quan sát chúng biến đổi theo thời gian.', controls: { rows: 'Hàng', columns: 'Cột', cycleTime: 'Thời gian chu kỳ (giây)' }, actions: { apply: 'Áp dụng', random: 'Ngẫu nhiên', start: 'Bắt đầu', clear: 'Xóa' }, counter: (cycleCounter) => `Chu kỳ: ${cycleCounter}`, repeatingState: 'Kết thúc trò chơi. Trạng thái đang lặp lại.', allCellsDead: 'Kết thúc trò chơi. Tất cả các ô đã chết.', toggleCell: ({ row, col }) => `Đổi trạng thái ô hàng ${row}, cột ${col}` },
  },
  footer: {
    title: 'Liên hệ', message: 'Nếu có câu hỏi, bạn có thể liên hệ với tôi qua email hoặc mạng xã hội.', socialAriaLabel: 'Liên kết mạng xã hội trong phần liên hệ',
    visitCounter: { title: 'Bộ đếm lượt truy cập', ariaLabel: 'Bộ đếm lượt xem trang', labels: { day: 'Hôm nay', week: '1 tuần', month: '1 tháng', year: '1 năm', allTime: 'Tổng cộng' } },
    notice: { site: 'Trang web cá nhân phi thương mại.', privacyPrefix: 'Tìm hiểu thêm: ', privacyLink: 'Quyền riêng tư và thông báo pháp lý', privacySuffix: '.' }, environmentsTitle: 'Môi trường', environmentsAriaLabel: 'Liên kết môi trường',
  },
  privacy: {
    title: 'Quyền riêng tư và thông báo pháp lý', lastUpdated: 'Cập nhật lần cuối: 20 tháng 8 năm 2026', sections: [
      { title: 'Mục đích phi thương mại', paragraphs: ['Trang web cá nhân này được xây dựng và duy trì để học tập, giới thiệu portfolio, giải trí và giao tiếp cá nhân. Đây không phải cửa hàng trực tuyến, sàn giao dịch, dịch vụ trả phí, dịch vụ cờ bạc hay tài chính, hoặc nền tảng tư vấn chuyên môn về pháp luật, y tế hay tài chính.', 'Trang web không nhằm thu lợi trực tiếp từ khách truy cập, bán dữ liệu của họ hoặc thu phí truy cập trò chơi, bài viết, trang hay thử nghiệm được đăng tại đây.'] },
      { title: 'Sử dụng cá nhân và giáo dục', paragraphs: ['Đây là dự án học tập và portfolio cá nhân. Mã nguồn, thử nghiệm giao diện, trò chơi và nội dung công khai có thể minh họa kỹ năng phát triển frontend, QA, kiểm thử, tự động hóa, thiết kế và kỹ thuật.', 'Ví dụ, cơ chế trò chơi, ảnh chụp màn hình, tài liệu tham khảo và tên gọi chỉ được dùng để giải thích, học tập, kiểm thử hoặc minh họa các ý tưởng phát triển web nói chung.'] },
      { title: 'Không có dịch vụ trả phí hay bán hàng', paragraphs: ['Trang web không xử lý thanh toán, không thu thập thông tin lập hóa đơn, không bán gói đăng ký hay sản phẩm kỹ thuật số trả phí. Nếu bổ sung chức năng thương mại trong tương lai, thông báo này sẽ được cập nhật trước khi công bố.'] },
      { title: 'Dữ liệu khách truy cập, tài khoản và liên hệ', paragraphs: ['Trang web có hoặc có thể có chức năng đăng ký và đăng nhập. Thông tin đăng ký có thể gồm tên, tên người dùng, email và mật khẩu. Trang web không chủ động yêu cầu thông tin thanh toán, giấy tờ tùy thân hay dữ liệu cá nhân nhạy cảm.', 'Trang web không gửi thư rác, bản tin tiếp thị hay quảng cáo không liên quan cho người đăng ký. Email chỉ được dùng để liên lạc về tài khoản, hỗ trợ khôi phục mật khẩu, trả lời trực tiếp hoặc gửi thông báo kỹ thuật cần thiết.', 'Không nên dùng lại mật khẩu từ các trang web, ứng dụng, email, ngân hàng, mạng xã hội hay hệ thống làm việc khác. Chủ trang web không chịu trách nhiệm về thiệt hại do mật khẩu dùng lại sau đó bị lộ, đoán ra, đánh cắp hoặc xâm phạm.', 'Khôi phục mật khẩu tự động có thể không phải lúc nào cũng khả dụng. Nếu cần, hãy gửi email đến antondorovs@gmail.com kèm đủ thông tin để xác định tài khoản.', 'Bạn cũng có thể liên hệ qua liên kết ngoài, mạng xã hội, dịch vụ nhắn tin hoặc ứng dụng email. Dịch vụ bên ngoài được chọn sẽ xử lý dữ liệu theo điều khoản và chính sách riêng.'] },
      { title: 'Phân tích và dịch vụ bên thứ ba', paragraphs: ['Trang web sử dụng Google Analytics, Yandex Metrica và Microsoft Clarity để hiểu lưu lượng truy cập, hiệu suất, lỗi và tương tác. Dữ liệu được xử lý có thể gồm URL trang, vị trí gần đúng suy ra từ mạng, thông tin trình duyệt và thiết bị, phiên truy cập, cookie hoặc mã định danh tương tự, lượt nhấp, cuộn và các tương tác khác.', 'Dữ liệu phân tích dùng để cải thiện chất lượng, tính dễ sử dụng, độ ổn định và nội dung. Chủ trang web không dùng dữ liệu này để xác định tên từng người, bán hồ sơ cá nhân hay cung cấp quảng cáo nhắm mục tiêu có trả phí.', 'Bộ đếm nội bộ lưu tổng hợp theo ngày UTC trong 365 ngày gần nhất và một tổng số riêng cho toàn bộ thời gian. Bộ đếm không lưu địa chỉ IP, tên, email, thông tin trình duyệt, cookie, mã thiết bị hoặc lịch sử cá nhân.', 'Google, Yandex và Microsoft xử lý dữ liệu theo điều khoản, chính sách riêng tư và cài đặt kỹ thuật của họ. Khi có sẵn, bạn có thể dùng cài đặt riêng tư của trình duyệt, trình chặn nội dung, công cụ quản lý cookie hoặc tùy chọn từ chối của nhà cung cấp.'] },
      { title: 'Cookie và localStorage', paragraphs: ['Trang web có thể dùng bộ nhớ trình duyệt để lưu tùy chọn giao diện. Giao diện và ngôn ngữ đã chọn được lưu trong localStorage giữa các phiên.', 'Bộ đếm nội bộ có thể tăng mỗi khi tải đầy đủ trang, kể cả làm mới. Các khoảng thời gian hiển thị là khoảng thời gian trượt kết thúc vào ngày UTC hiện tại, không phải tuần, tháng hay năm theo lịch. Bộ đếm không xác định khách truy cập duy nhất và không loại bỏ lượt truy cập lặp lại.', 'Công cụ phân tích bên ngoài có thể dùng cookie hoặc công nghệ tương tự. Cách hoạt động phụ thuộc vào trình duyệt, khu vực, cài đặt riêng tư và cấu hình hiện tại của nhà cung cấp.'] },
      { title: 'Dự án trò chơi và quyền của bên thứ ba', paragraphs: ['Các trò chơi trình duyệt là dự án học tập cá nhân, lấy cảm hứng từ cơ chế phổ biến và khái niệm trò chơi arcade quen thuộc. Chúng không phải phiên bản chính thức, bản chuyển thể được cấp phép, bản làm lại thương mại hay sản phẩm thay thế trò chơi gốc.', 'Trang web không tuyên bố sở hữu nhân vật, nhãn hiệu, tên trò chơi, ý tưởng, âm thanh, phong cách hình ảnh hoặc tư liệu gốc của người khác. Tư liệu có thể xâm phạm quyền hợp pháp sẽ được xem xét và gỡ bỏ hoặc thay thế khi có yêu cầu hợp lý.'] },
      { title: 'Nhãn hiệu, tên gọi và bản quyền', paragraphs: ['Nhãn hiệu, tên công ty, sản phẩm, dịch vụ, logo và tác phẩm được bảo hộ thuộc về chủ sở hữu tương ứng. Trừ khi có ghi rõ, việc xuất hiện trên trang không ngụ ý sự chấp thuận, tài trợ, hợp tác hay liên kết.', 'Văn bản, mã nguồn, bố cục và tư liệu cá nhân do chủ trang tạo được đăng để giới thiệu portfolio và phục vụ giáo dục. Không nên sao chép vào sản phẩm thương mại khi chưa được phép.'] },
      { title: 'Liên kết ngoài', paragraphs: ['Trang web có thể liên kết đến trang bên ngoài, mạng xã hội, kho mã nguồn, dịch vụ nhắn tin, công cụ phát triển, dịch vụ phân tích hoặc môi trường dự án. Các trang đó do đơn vị tương ứng quản lý và có thể thu thập dữ liệu theo chính sách riêng.', 'Chủ trang web không chịu trách nhiệm về nội dung bên ngoài, cách xử lý quyền riêng tư của bên ngoài hay tính khả dụng của dịch vụ bên thứ ba.'] },
      { title: 'Liên hệ', paragraphs: ['Nếu có câu hỏi về trang web, quyền riêng tư, thông báo pháp lý, việc gỡ bỏ nội dung hoặc quyền sở hữu, hãy dùng thông tin liên hệ công khai trên trang chủ. Vui lòng cung cấp đủ ngữ cảnh để xác định trang, tư liệu hoặc vấn đề cần xử lý.'] },
    ],
  },
};
