import { createAdditionalTranslation } from './createAdditionalTranslation.js';

// Danish translation draft; native-speaker review is still recommended.
export const daTranslation = createAdditionalTranslation('da', {
  nav: ['Om mig', 'Erfaring', 'Spil', 'Kontakt'],
  labels: {
    navigation: 'Hovednavigation', mobileNavigation: 'Mobilnavigation', openMenu: 'Åbn menuen', closeMenu: 'Luk menuen', theme: 'Tema', system: 'System', language: 'Sprog', signInInfo: 'Oplysninger om login', underDevelopment: 'Denne funktion er under udvikling', profile: 'Profil', social: 'Links til sociale medier', summary: 'Faglig profil', cv: 'CV', work: 'Erhvervserfaring', education: 'Uddannelse og kurser', skills: 'Kompetencer og værktøjer', cvEn: 'Åbn CV på engelsk (PDF)', cvRu: 'Åbn CV på russisk (PDF)', stack: 'Teknologier', gameBoard: 'Spillefelt', score: 'Point', gameOver: 'Spillet er slut.', restart: 'Start forfra', counter: 'Besøgstæller', personalSite: 'Personlig, ikke-kommerciel hjemmeside.', details: 'Læs mere:', environments: 'Miljøer',
  },
  greeting: 'Hej alle sammen!',
  summary: ['Velkommen til min personlige porteføljeside.', 'Jeg er Full Stack QA Engineer med speciale i manuel og automatiseret test af frontend, backend samt web- og mobilapplikationer. Her finder du mit CV, oplysninger om min erhvervserfaring, uddannelse og gennemførte kurser samt mine kontaktoplysninger.', 'Du kan også spille browserspil, som jeg laver i min fritid som led i mine tekniske eksperimenter. Jeg håber, du vil synes om siden.'],
  about: [
    'Jeg har en ingeniørfaglig baggrund. Jeg er uddannet fra Bauman Moskva Statslige Tekniske Universitet med fokus på konstruktion og programmering af elektroniske enheder.',
    'Før jeg skiftede til IT, arbejdede jeg inden for flere ingeniørområder, herunder ubemandede luftfartssystemer og industriudstyr. På nogle projekter koordinerede jeg også teamets arbejde og havde ansvar for tekniske og organisatoriske opgaver.',
    'Jeg arbejder nu som QA-ingeniør og videreudvikler mine færdigheder inden for testautomatisering og programmering. Jeg vil ikke kun finde fejl, men også forstå hele systemet, fra brugergrænsefladen og API til integrationer og infrastruktur. Test skal efter min mening reelt forbedre produktets kvalitet og brugervenlighed og ikke blot være en formalitet.',
    'Jeg underviser og vejleder nye QA-specialister. Jeg har gode kommunikationsevner, stor motivation og en ansvarsbevidst tilgang.',
    'I min fritid dyrker jeg fridykning, vandring, sejlads og kropsvægtstræning. Jeg holder også af at rejse og besøge forskellige lande.',
  ],
  work: [{ period: 'Aug. 2024 – nu', before: 'Udvikling af sælgerplatformen ', after: ' til pakkehåndtering.' }, { period: 'Maj 2022 – aug. 2024', before: 'VTB Banks kontantlogistikprojekt fra ', after: ' til automatisering af kontantindsamling og prognoser for servicering af hæveautomater.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – nu | Engelskkurser | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Bauman Moskva Statslige Tekniske Universitet | Fakultet for radioteknik | Konstruktion og produktionsteknologi for radioelektroniske enheder | Karaktergennemsnit: 4,05.'],
  skillTitles: ['Test', 'Automatisering og IDE', 'API og data', 'Infrastruktur og logfiler', 'Mobil og browserkompatibilitet', 'Produkt og processer'],
  life: {
    description: ['Game of Life er en cellulær automat, som matematikeren John Conway udviklede i 1970. Det er et spil uden spillere: udviklingen bestemmes af starttilstanden uden yderligere input. Spillefeltet er et gitter af celler, der enten er levende eller døde.', 'Udviklingen følger enkle regler:'],
    rules: ['En levende celle med færre end to levende naboer dør af underbefolkning.', 'En levende celle med to eller tre levende naboer overlever til næste generation.', 'En levende celle med flere end tre levende naboer dør af overbefolkning.', 'En død celle med præcis tre levende naboer bliver levende.'],
    interaction: 'Klik på cellerne for at ændre deres tilstand. Prøv forskellige startmønstre, og se, hvordan de udvikler sig med tiden.', controls: ['Rækker', 'Kolonner', 'Cyklustid (sek.)'], cycle: 'Cyklus', repeatingState: 'Spillet er slut. En tidligere tilstand gentager sig.', allCellsDead: 'Spillet er slut. Alle celler er døde.', toggleCell: 'Skift cellens tilstand',
  },
  contactMessage: 'Du kan kontakte mig via e-mail eller sociale medier, hvis du har spørgsmål.', periods: ['I dag', '1 uge', '1 måned', '1 år', 'I alt'],
  privacy: {
    title: 'Privatlivspolitik og juridiske oplysninger', lastUpdated: 'Senest opdateret: 20. august 2026', sections: [
      { title: 'Ikke-kommercielt formål', paragraphs: ['Denne personlige hjemmeside vedligeholdes til læring, portefølje, underholdning og personlig kommunikation. Den er ikke en netbutik, markedsplads, betalingstjeneste, spilletjeneste med pengeindsatser, finansiel tjeneste eller platform for professionel juridisk, lægelig eller finansiel rådgivning.', 'Siden har ikke til formål at tjene direkte på besøgende, sælge deres data eller opkræve betaling for adgang til browserspil, artikler, sider eller eksperimenter.'] },
      { title: 'Personlig brug og læring', paragraphs: ['Siden er et personligt læringsprojekt og en portefølje. Kode, grænsefladeeksperimenter, browserspil og offentligt indhold kan demonstrere kompetencer inden for frontend, QA, test, automatisering, design og teknik.', 'Eksempler, spilmekanikker, skærmbilleder, henvisninger og navne bruges kun til at forklare, lære, teste eller demonstrere almindelige idéer inden for webudvikling.'] },
      { title: 'Ingen betalte tjenester eller salg', paragraphs: ['Siden behandler ikke betalinger, indsamler ikke faktureringsoplysninger og sælger hverken abonnementer eller digitale produkter. Hvis kommercielle funktioner tilføjes senere, skal denne politik opdateres, før de offentliggøres.'] },
      { title: 'Besøgs-, konto- og kontaktdata', paragraphs: ['Siden indeholder eller kan komme til at indeholde registrering og login. Registreringsdata kan omfatte navn, kaldenavn, e-mail og adgangskode. Der anmodes ikke bevidst om betalingsoplysninger, identitetsdokumenter eller følsomme personoplysninger ved registrering.', 'Registrerede brugere får ikke spam, markedsføringsnyhedsbreve eller uvedkommende reklamer. E-mail bruges kun til kontorelateret kommunikation, hjælp med adgangskoder, direkte svar eller nødvendige tekniske meddelelser.', 'Genbrug ikke adgangskoder fra andre hjemmesider, apps, e-mailkonti, banker, sociale netværk eller arbejdspladssystemer. Ejeren er ikke ansvarlig for skade ved genbrug af en adgangskode, som senere lækkes, gættes, stjæles eller kompromitteres andetsteds.', 'Automatisk gendannelse af adgangskoder er ikke altid tilgængelig. Skriv om nødvendigt til antondorovs@gmail.com med tilstrækkelige kontooplysninger til at identificere anmodningen.', 'Ved kontakt gennem eksterne links, sociale platforme, beskedtjenester eller e-mailprogrammer behandles data af den valgte tjeneste efter dens egne vilkår og privatlivspolitik.'] },
      { title: 'Analyse og tredjepartstjenester', paragraphs: ['Google Analytics, Yandex Metrica og Microsoft Clarity bruges til at forstå trafik, ydelse, fejl og brugerinteraktion. De kan behandle sideadresser, omtrentlig placering udledt af netværksdata, browser- og enhedsoplysninger, sessioner, cookies eller lignende identifikatorer, klik, rulning og anden interaktion.', 'Analysedata bruges til at forbedre kvalitet, brugervenlighed, stabilitet og indhold, ikke til at identificere besøgende ved navn, sælge personprofiler eller tilbyde betalt målrettet reklame.', 'Den interne sidetæller gemmer samlede dagstal i UTC for de seneste 365 dage samt et separat samlet tal for hele perioden. Den gemmer ikke IP-adresser, navne, e-mailadresser, browseroplysninger, cookies, enhedsidentifikatorer eller individuelle besøgshistorikker.', 'Google, Yandex og Microsoft behandler data efter egne vilkår, privatlivspolitikker og tekniske indstillinger. Du kan bruge browserens privatlivsindstillinger, indholdsblokering, cookieindstillinger eller udbydernes fravalgsværktøjer, hvor de findes.'] },
      { title: 'Cookies og lokal lagring', paragraphs: ['Siden kan bruge browserlagring til grænsefladeindstillinger. Valgt tema og sprog gemmes i localStorage mellem besøg.', 'Tælleren kan stige ved hver fuld sideindlæsning, også genindlæsninger. Perioderne er rullende tidsvinduer frem til den aktuelle UTC-dato, ikke kalenderuger, -måneder eller -år. Den identificerer eller deduplikerer ikke individuelle besøgende.', 'Tredjepartsanalyse kan bruge cookies og lignende teknologier. Adfærden afhænger af browser, region, privatlivsindstillinger og udbydernes aktuelle opsætning.'] },
      { title: 'Spilprojekter og tredjepartsrettigheder', paragraphs: ['Browserspillene er personlige læringsprojekter inspireret af almindelige webspilmekanikker og kendte arkadekoncepter. De er ikke officielle udgaver, licenserede tilpasninger, kommercielle genudgivelser eller erstatninger for originalerne.', 'Siden gør ikke krav på andres figurer, mærker, spiltitler, varemærker, koncepter, lyde, visuelle stilarter eller originalmateriale. Materiale, der kan krænke legitime rettigheder, vil blive vurderet og fjernet eller erstattet efter en rimelig henvendelse.'] },
      { title: 'Varemærker, navne og ophavsret', paragraphs: ['Omtalte varemærker, firma-, produkt- og tjenestenavne, logoer og ophavsretligt beskyttede værker tilhører deres respektive ejere. Omtale indebærer ikke godkendelse, sponsorat, partnerskab eller tilknytning, medmindre det udtrykkeligt fremgår.', 'Original tekst, kode, layout og personlige materialer offentliggøres til portefølje- og undervisningsformål. De må ikke kopieres til kommercielle produkter uden tilladelse.'] },
      { title: 'Eksterne links', paragraphs: ['Siden kan linke til eksterne hjemmesider, sociale netværk, kodearkiver, beskedtjenester, udviklingsværktøjer, analyseudbydere og projektmiljøer. Disse styres af deres egne ejere og kan indsamle data efter egne politikker.', 'Ejeren er ikke ansvarlig for eksternt indhold, eksterne privatlivspraksisser eller tredjepartstjenesters tilgængelighed.'] },
      { title: 'Kontakt', paragraphs: ['Ved spørgsmål om siden, privatliv, juridiske oplysninger, fjernelse af indhold eller rettigheder kan du bruge kontaktlinkene på forsiden. Medtag nok oplysninger til at identificere siden, materialet eller problemet.'] },
    ],
  },
});
