import { createAdditionalTranslation } from './createAdditionalTranslation.js';

export const isTranslation = createAdditionalTranslation('is', {
  nav: ['Um mig', 'Reynsla', 'Leikir', 'Samskipti'],
  labels: { navigation: 'Aðalvalmynd', mobileNavigation: 'Farsímavalmynd', openMenu: 'Opna valmynd', closeMenu: 'Loka valmynd', theme: 'Þema', system: 'Kerfi', language: 'Tungumál', signInInfo: 'Upplýsingar um innskráningu', underDevelopment: 'Þessi virkni er í þróun', profile: 'Persónusnið', social: 'Tenglar á samfélagsmiðla', summary: 'Starfsyfirlit', cv: 'Ferilskrá', work: 'Starfsreynsla', education: 'Menntun og námskeið', skills: 'Færni og verkfæri', cvEn: 'Opna ferilskrá á ensku (PDF)', cvRu: 'Opna ferilskrá á rússnesku (PDF)', stack: 'Tæknilausnir', gameBoard: 'Leikborð', score: 'Stig', gameOver: 'Leik lokið.', restart: 'Byrja aftur', counter: 'Heimsóknateljari', personalSite: 'Persónuleg vefsíða án viðskiptatilgangs.', details: 'Nánari upplýsingar:', environments: 'Umhverfi' },
  greeting: 'Halló öll!',
  summary: ['Velkomin á persónulega verkefnasafnið mitt.', 'Ég er Full Stack QA Engineer og sérhæfi mig í handvirkum og sjálfvirkum prófunum á framenda, bakenda, vef- og farsímaforritum. Hér má finna ferilskrána mína, upplýsingar um starfsreynslu, menntun og lokin námskeið ásamt samskiptaupplýsingum.', 'Einnig er hægt að spila vafraleiki sem ég bý til í frítíma mínum sem hluta af tæknilegum tilraunum. Ég vona að þér líki við síðuna.'],
  about: ['Ég hef verkfræðilegan bakgrunn. Ég lauk námi við Bauman-tækniháskólann í Moskvu með áherslu á hönnun og forritun rafeindatækja.', 'Áður en ég fór í upplýsingatækni vann ég á nokkrum verkfræðisviðum, meðal annars við ómönnuð loftför og iðnaðarbúnað. Í sumum verkefnum samræmdi ég líka vinnu teymis og bar ábyrgð á tæknilegum og skipulagslegum verkefnum.', 'Ég starfa nú sem QA-verkfræðingur og held áfram að efla færni mína í sjálfvirknivæðingu prófana og forritun. Ég vil ekki aðeins finna villur heldur skilja allt kerfið, frá notendaviðmóti og API til samþættinga og innviða. Prófanir eiga að bæta gæði og notagildi vörunnar í raun, ekki aðeins vera formsatriði.', 'Ég þjálfa og leiðbeini nýjum QA-sérfræðingum. Ég hef góða samskiptahæfni, mikinn áhuga og ábyrg vinnubrögð.', 'Í frítíma mínum stunda ég meðal annars fríköfun, gönguferðir, siglingar og líkamsþyngdaræfingar. Mér finnst einnig gaman að ferðast og heimsækja ólík lönd.'],
  work: [{ period: 'Ágúst 2024 – nú', before: 'Þróun sölukerfisins ', after: ' fyrir pakkastjórnun.' }, { period: 'Maí 2022 – ágúst 2024', before: 'Verkefni VTB Bank um flutninga reiðufjár frá ', after: ' til að sjálfvirknivæða söfnun reiðufjár og spá fyrir um þjónustuþörf hraðbanka.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – nú | Enskunámskeið | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Bauman-tækniháskólinn í Moskvu | Deild fjarskiptaverkfræði | Hönnun og framleiðslutækni radíó- og rafeindatækja | Meðaleinkunn: 4,05.'],
  skillTitles: ['Prófanir', 'Sjálfvirknivæðing og IDE', 'API og gögn', 'Innviðir og annálar', 'Farsímar og vafrasamhæfni', 'Vara og ferli'],
  life: { description: ['Game of Life er frumuvél sem stærðfræðingurinn John Conway bjó til árið 1970. Þetta er leikur án leikmanna: upphafsástandið ákvarðar framvinduna án frekari inngripa. Leikborðið er reitanet þar sem hver fruma er annaðhvort lifandi eða dauð.', 'Framvindan fylgir einföldum reglum:'], rules: ['Lifandi fruma með færri en tvo lifandi nágranna deyr vegna fólksfæðar.', 'Lifandi fruma með tvo eða þrjá lifandi nágranna lifir áfram í næstu kynslóð.', 'Lifandi fruma með fleiri en þrjá lifandi nágranna deyr vegna offjölgunar.', 'Dauð fruma með nákvæmlega þrjá lifandi nágranna lifnar við.'], interaction: 'Smelltu á frumur til að breyta ástandi þeirra. Prófaðu ólík upphafsmynstur og fylgstu með þróun þeirra.', controls: ['Raðir', 'Dálkar', 'Lengd umferðar (sek.)'], cycle: 'Umferð', repeatingState: 'Leik lokið. Fyrra ástand endurtekur sig.', allCellsDead: 'Leik lokið. Allar frumur eru dauðar.', toggleCell: 'Breyta ástandi frumu' },
  contactMessage: 'Hafðu samband með tölvupósti eða á samfélagsmiðlum ef þú hefur spurningar.', periods: ['Í dag', '1 vika', '1 mánuður', '1 ár', 'Samtals'],
  privacy: { title: 'Persónuvernd og lagalegar upplýsingar', lastUpdated: 'Síðast uppfært: 20. ágúst 2026', sections: [
    { title: 'Enginn viðskiptatilgangur', paragraphs: ['Þessi persónulega vefsíða er rekin til náms, kynningar verkefna, afþreyingar og persónulegra samskipta. Hún er ekki netverslun, markaðstorg, gjaldskyld þjónusta, fjárhættuspila- eða fjármálaþjónusta né vettvangur faglegrar laga-, læknis- eða fjármálaráðgjafar.', 'Markmiðið er ekki að afla beinna tekna af gestum, selja gögn þeirra eða rukka fyrir aðgang að vafraleikjum, greinum, síðum eða tilraunum.'] },
    { title: 'Persónuleg notkun og nám', paragraphs: ['Vefsíðan er persónulegt námsverkefni og verkefnasafn. Kóði, viðmótstilraunir, vafraleikir og opinbert efni geta sýnt færni í framendaþróun, QA, prófunum, sjálfvirknivæðingu, hönnun og verkfræði.', 'Dæmi, leikjakerfi, skjáskot, tilvísanir og nöfn eru aðeins notuð til útskýringa, náms, prófana eða sýnikennslu á algengum hugmyndum í vefþróun.'] },
    { title: 'Engin sala eða gjaldskyld þjónusta', paragraphs: ['Síðan vinnur ekki úr greiðslum, safnar ekki greiðsluupplýsingum og selur hvorki áskriftir né stafrænar vörur. Verði viðskiptaeiginleikum bætt við þarf að uppfæra þessa stefnu áður en þeir eru birtir.'] },
    { title: 'Gögn gesta, aðgangsgögn og samskipti', paragraphs: ['Síðan inniheldur eða kann að innihalda nýskráningu og innskráningu. Skráning getur falið í sér nafn, gælunafn, tölvupóstfang og lykilorð. Ekki er vísvitandi óskað eftir greiðsluupplýsingum, persónuskilríkjum eða viðkvæmum persónuupplýsingum.', 'Skráðir notendur fá ekki ruslpóst, markaðsfréttabréf eða ótengdar auglýsingar. Tölvupóstur er aðeins notaður vegna aðgangs, aðstoðar við endurheimt lykilorðs, beinna svara eða nauðsynlegra tæknitilkynninga.', 'Ekki endurnýta lykilorð frá öðrum vefsíðum, forritum, tölvupósti, bönkum, samfélagsmiðlum eða vinnukerfum. Eigandinn ber ekki ábyrgð á tjóni vegna endurnýtts lykilorðs sem síðar lekur, er giskað á, stolið eða kemst í hendur annarra annars staðar.', 'Sjálfvirk endurheimt lykilorðs er ekki alltaf tiltæk. Ef þörf krefur má senda tölvupóst á antondorovs@gmail.com með nægum upplýsingum um aðganginn til að auðkenna beiðnina.', 'Við samskipti í gegnum ytri tengla, samfélagsmiðla, skilaboðaþjónustur eða tölvupóstforrit sér viðkomandi þjónusta um gögnin samkvæmt eigin skilmálum og persónuverndarstefnu.'] },
    { title: 'Greining og þjónusta þriðju aðila', paragraphs: ['Google Analytics, Yandex Metrica og Microsoft Clarity eru notuð til að skilja umferð, afköst, villur og samskipti gesta við síðuna. Þau geta unnið með vefslóðir, áætlaða staðsetningu út frá netgögnum, upplýsingar um vafra og tæki, setur, vafrakökur eða sambærileg auðkenni, smelli, skrunið og önnur samskipti.', 'Greiningargögn eru notuð til að bæta gæði, notagildi, stöðugleika og efni, ekki til að bera kennsl á gesti með nafni, selja persónusnið eða bjóða gjaldskyldar markvissar auglýsingar.', 'Innri síðuhleðsluteljari geymir samanlagðar dagstölur í UTC fyrir síðustu 365 daga og sérstaka heildartölu. Hann geymir ekki IP-tölur, nöfn, tölvupóstföng, vafraupplýsingar, vafrakökur, tækjaauðkenni eða heimsóknasögu einstaklinga.', 'Google, Yandex og Microsoft vinna með gögn eftir eigin skilmálum, persónuverndarreglum og tæknistillingum. Gestir geta notað persónuverndarstillingar vafra, efnisblokkara, vafrakökustillingar eða afþökkunartól þjónustuaðila þar sem þau eru tiltæk.'] },
    { title: 'Vafrakökur og staðbundin geymsla', paragraphs: ['Vefsíðan getur notað geymslu vafrans fyrir viðmótsstillingar. Valið þema og tungumál eru vistuð í localStorage milli heimsókna.', 'Teljarinn getur hækkað við hverja heila síðuhleðslu, einnig endurhleðslu. Tímabilin eru hlaupandi gluggar sem enda á núverandi UTC-degi en ekki almanaksvikur, -mánuðir eða -ár. Hann greinir ekki einstaka gesti eða sameinar endurteknar heimsóknir þeirra.', 'Greiningartól þriðju aðila geta notað vafrakökur og sambærilega tækni. Hegðunin fer eftir vafra, svæði, persónuverndarvali og núverandi stillingum þjónustuaðila.'] },
    { title: 'Leikjaverkefni og réttindi þriðju aðila', paragraphs: ['Vafraleikirnir eru persónuleg námsverkefni innblásin af algengum vefleikjakerfum og þekktum spilakassahugmyndum. Þeir eru ekki opinberar útgáfur, leyfðar aðlaganir, endurgerðir í viðskiptaskyni eða staðgenglar frumleikja.', 'Síðan gerir ekki tilkall til persóna, merkja, leikjaheita, vörumerkja, hugmynda, hljóða, sjónræns stíls eða upprunaefnis annarra. Ef efni kann að brjóta gegn lögmætum réttindum verður það skoðað og fjarlægt eða því skipt út eftir eðlilega beiðni.'] },
    { title: 'Vörumerki, nöfn og höfundarréttur', paragraphs: ['Öll nefnd vörumerki, fyrirtækja-, vöru- og þjónustuheiti, lógó og höfundarréttarvarin verk eru eign viðkomandi rétthafa. Birting felur ekki í sér samþykki, kostun, samstarf eða tengsl nema það sé tekið sérstaklega fram.', 'Frumtexti, kóði, uppsetning og persónulegt efni eru birt til kynningar verkefna og náms. Ekki má afrita þau í viðskiptavörur án leyfis.'] },
    { title: 'Ytri tenglar', paragraphs: ['Síðan getur tengt á aðrar vefsíður, samfélagsmiðla, kóðasöfn, skilaboðaþjónustur, þróunartól, greiningarþjónustur og verkefnaumhverfi. Þau eru í stjórn eigin eigenda og geta safnað gögnum samkvæmt eigin stefnu.', 'Eigandinn ber ekki ábyrgð á ytra efni, persónuverndarvenjum annarra eða aðgengi að þjónustu þriðju aðila.'] },
    { title: 'Samskipti', paragraphs: ['Notaðu samskiptatenglana á forsíðunni vegna spurninga um síðuna, persónuvernd, lagalegar upplýsingar, fjarlægingu efnis eða réttindi. Gefðu nægt samhengi til að auðkenna síðuna, efnið eða vandann.'] },
  ] },
});
