import { createAdditionalTranslation } from './createAdditionalTranslation.js';

// Translation draft; native-speaker review is recommended.
export const haTranslation = createAdditionalTranslation('ha', {
  nav: ['Game da ni', 'Ƙwarewa', 'Wasanni', 'Tuntuɓa'],
  labels: { navigation: 'Babban kewayawa', mobileNavigation: 'Kewayawa a waya', openMenu: 'Buɗe menu', closeMenu: 'Rufe menu', theme: 'Jigo', system: 'Na tsarin na’ura', language: 'Harshe', signInInfo: 'Bayanin shiga', underDevelopment: 'Ana ci gaba da gina wannan fasalin', profile: 'Bayanan mutum', social: 'Hanyoyin sada zumunta', summary: 'Taƙaitaccen bayanin aiki', cv: 'CV', work: 'Tarihin aiki', education: 'Ilimi da kwasa-kwasai', skills: 'Ƙwarewa da kayan aiki', cvEn: 'Buɗe CV na Turanci (PDF)', cvRu: 'Buɗe CV na Rashanci (PDF)', stack: 'Fasahohi', gameBoard: 'Filin wasa', score: 'Maki', gameOver: 'An gama wasa.', restart: 'Sake farawa', counter: 'Ƙidayar ziyara', personalSite: 'Shafin mutum wanda ba na kasuwanci ba.', details: 'Ƙarin bayani:', environments: 'Muhallan aiki' },
  greeting: 'Sannu kowa da kowa!',
  summary: ['Barka da zuwa shafina na nuna ayyukana.', 'Ni Full Stack QA Engineer ne, na ƙware a gwajin hannu da na atomatik na frontend, backend, manhajojin yanar gizo da na wayar hannu. A nan za ku sami CV na, tarihin aikina, ilimina, kwasa-kwasan da na kammala da hanyoyin tuntuɓata.', 'Haka kuma za ku iya buga wasannin burauza da nake ƙirƙira a lokacin hutu a matsayin gwaje-gwajen fasaha. Ina fatan shafin zai burge ku.'],
  about: ['Ina da ilimin injiniya. Na kammala karatu a Bauman Moscow State Technical University, inda na mayar da hankali kan zane da tsara shirye-shiryen na’urorin lantarki.', 'Kafin shiga IT, na yi aiki a fannoni da dama na injiniya, ciki har da jiragen da ba su da matuƙi da kayan masana’antu. A wasu ayyukan na kuma tsara aikin ƙungiya, tare da ɗaukar nauyin harkokin fasaha da gudanarwa.', 'Yanzu ina aiki a matsayin injiniyan QA, kuma ina ci gaba da haɓaka ƙwarewata a gwaji na atomatik da shirye-shiryen kwamfuta. Ba gano kurakurai kaɗai nake so ba, har ma da fahimtar tsarin gaba ɗaya: UI, API, haɗin tsarin da kayayyakin more rayuwa. Gwaji ya kamata ya inganta inganci da sauƙin amfani da samfur, ba ya zama cika ƙa’ida kawai ba.', 'Ina koyarwa da ba sabbin ƙwararrun QA jagora. Ina da kyakkyawar sadarwa, himma da ɗaukar alhaki a aiki.', 'A lokacin hutu ina son nutsewa ba tare da tankin iska ba, tafiya a daji, tuƙin jirgin ruwa da atisayen nauyin jiki. Ina kuma son tafiya zuwa ƙasashe daban-daban.'],
  work: [{ period: 'Agusta 2024 – yanzu', before: 'Gina dandalin masu sayarwa ', after: ' don kula da kunshe-kunshe.' }, { period: 'Mayu 2022 – Agusta 2024', before: 'Aikin jigilar kuɗi na bankin VTB daga ', after: ' don sarrafa tattara kuɗi ta atomatik da hasashen lokacin kula da ATM.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – yanzu | Kwasa-kwasan Turanci | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Bauman Moscow State Technical University | Sashen injiniyan rediyo | Zane da fasahar kera na’urorin rediyo da lantarki | Matsakaicin maki: 4.05.'],
  skillTitles: ['Gwaji', 'Aiki na atomatik da IDE', 'API da bayanai', 'Tsarin aiki da rajistoci', 'Wayar hannu da burauzoci daban-daban', 'Samfur da matakan aiki'],
  life: { description: ['Game of Life tsarin ƙwayoyin lissafi ne da masanin lissafi John Conway ya ƙirƙira a 1970. Wasa ne marar ɗan wasa: yanayin farko ne ke ƙayyade yadda zai sauya, ba tare da ƙarin umarni ba. Filin yana da ƙwayoyi a layuka; kowace tana raye ko ta mutu.', 'Yana sauyawa bisa ƙa’idoji masu sauƙi:'], rules: ['Ƙwayar da ke raye mai maƙwabta masu rai ƙasa da biyu tana mutuwa saboda ƙarancin jama’a.', 'Ƙwayar da ke raye mai maƙwabta masu rai biyu ko uku tana ci gaba da rayuwa a zagaye na gaba.', 'Ƙwayar da ke raye mai maƙwabta masu rai fiye da uku tana mutuwa saboda cunkoso.', 'Matacciyar ƙwaya mai maƙwabta masu rai uku cif tana rayuwa.'], interaction: 'Danna ƙwayoyin don canza yanayinsu. Gwada tsare-tsaren farko daban-daban, ka ga yadda suke sauyawa da lokaci.', controls: ['Layuka', 'Ginshiƙai', 'Tsawon zagaye (daƙiƙa)'], cycle: 'Zagaye', repeatingState: 'An gama wasa. An maimaita yanayin da ya gabata.', allCellsDead: 'An gama wasa. Dukkan ƙwayoyi sun mutu.', toggleCell: 'Canza yanayin ƙwaya' },
  contactMessage: 'Idan kuna da tambaya, ku tuntuɓe ni ta imel ko kafofin sada zumunta.', periods: ['Yau', 'Mako 1', 'Wata 1', 'Shekara 1', 'Jimilla'],
  privacy: { title: 'Sirri da bayanan doka', lastUpdated: 'Sabuntawa ta ƙarshe: 20 Agusta 2026', sections: [
    { title: 'Manufa ba ta kasuwanci ba', paragraphs: ['Wannan shafin mutum ne don koyo, nuna ayyuka, nishaɗi da sadarwa. Ba shagon yanar gizo ba ne, ba kasuwa ba, ba sabis na kuɗi ko caca ba, kuma ba dandali ne na ƙwararrun shawarwarin doka, lafiya ko harkokin kuɗi ba.', 'Ba a yi shafin don samun kuɗi kai tsaye daga baƙi, sayar da bayanansu ko karɓar kuɗin shiga wasanni, rubuce-rubuce, shafuka ko gwaje-gwaje ba.'] },
    { title: 'Amfanin mutum da koyo', paragraphs: ['Shafin aikin koyo da nuna ƙwarewar mutum ne. Lamba, gwaje-gwajen fuskar amfani, wasannin burauza da bayanan jama’a na iya nuna ƙwarewa a frontend, QA, gwaji, sarrafa aiki ta atomatik, zane da injiniya.', 'Ana amfani da misalai, tsarin wasanni, hotunan allo, manazarta da sunaye ne kawai don bayani, koyo, gwaji ko nuna ra’ayoyin gina yanar gizo.'] },
    { title: 'Babu sabis na biya ko sayarwa', paragraphs: ['Shafin ba ya karɓar biyan kuɗi, tattara bayanan lissafin kuɗi ko sayar da rajistar biya da kayan dijital. Idan an ƙara fasalolin kasuwanci nan gaba, dole a sabunta wannan manufa kafin a wallafa su.'] },
    { title: 'Bayanan baƙi, asusu da tuntuɓa', paragraphs: ['Shafin yana da ko zai iya samun rajista da shiga asusu. Bayanan rajista na iya haɗa suna, laƙabi, imel da kalmar sirri. Ba a neman bayanan biya, takardun shaida ko bayanan sirri masu matuƙar muhimmanci da gangan ba.', 'Ba a aika wa masu rajista spam, wasiƙun talla ko tallace-tallacen da ba su da alaƙa. Ana amfani da imel don asusu, taimakon dawo da kalmar sirri, amsa kai tsaye ko muhimman saƙonnin fasaha kawai.', 'Kada ku sake amfani da kalmar sirri ta wasu shafuka, manhajoji, imel, bankuna, kafofin sada zumunta ko tsarin aiki. Mai shafin ba ya ɗaukar alhakin lahani sakamakon sake amfani da kalmar sirri wadda ta zube, aka hango, aka sace ko aka karya a wani wuri.', 'Dawo da kalmar sirri ta atomatik na iya zama babu shi. Idan ya zama dole, aika saƙo zuwa antondorovs@gmail.com tare da isassun bayanan asusu don gano buƙatar.', 'Idan kuka tuntuɓa ta hanyoyin waje, sada zumunta, saƙonni ko manhajar imel, sabis ɗin da kuka zaɓa ne ke sarrafa bayanai bisa sharuɗɗansa da manufar sirrinsa.'] },
    { title: 'Binciken amfani da sabis na wasu', paragraphs: ['Ana amfani da Google Analytics, Yandex Metrica da Microsoft Clarity don fahimtar zirga-zirga, saurin aiki, kurakurai da mu’amala. Za su iya sarrafa adireshin shafi, wurin kusan da bayanan hanyar sadarwa ke nunawa, burauza da na’ura, zama, cookies ko makamantan alamomi, dannawa, gungurawa da sauran mu’amala.', 'Ana amfani da bincike don inganta inganci, sauƙin amfani, kwanciyar hankali da abun ciki, ba don gano baƙi da suna, sayar da bayanan mutum ko tallar biya mai niyya ba.', 'Ƙidayar loda shafi ta cikin gida tana adana jimillar kowace rana bisa UTC na kwanaki 365 da suka gabata da jimillar duk lokaci daban. Ba ta adana adireshin IP, suna, imel, bayanan burauza, cookies, shaidar na’ura ko tarihin ziyara na mutum.', 'Google, Yandex da Microsoft suna sarrafa bayanai bisa nasu sharuɗɗa, manufofin sirri da saitunan fasaha. Za ku iya amfani da saitunan sirri na burauza, masu toshe abun ciki, saitunan cookies ko kayan ƙin shiga na masu ba da sabis idan suna nan.'] },
    { title: 'Cookies da ma’ajiyar cikin na’ura', paragraphs: ['Shafin na iya amfani da ma’ajiyar burauza don saitunan fuskar amfani. Ana adana jigo da harshen da aka zaɓa a localStorage tsakanin ziyara.', 'Ƙidaya na iya ƙaruwa duk lokacin da aka loda shafi gaba ɗaya, har da sake loda shi. Lokutan jeri masu motsi ne zuwa ranar UTC ta yanzu, ba makonni, watanni ko shekarun kalanda ba. Ba ta gano mutum ko cire maimaitattun ziyara.', 'Binciken wasu na iya amfani da cookies da makamantan fasahohi. Halayensu sun dogara da burauza, yanki, saitunan sirri da tsarin mai ba da sabis na yanzu.'] },
    { title: 'Ayyukan wasanni da haƙƙin wasu', paragraphs: ['Wasannin burauza ayyukan koyo na mutum ne, bisa tsarin wasannin yanar gizo da sanannun ra’ayoyin arcade. Ba sigogin hukuma ba ne, ba kwafin lasisi ba, ba sake-ginin kasuwanci ko madadin asali ba.', 'Shafin ba ya ikirarin mallakar jarumai, alamomi, sunayen wasa, alamun kasuwanci, ra’ayoyi, sauti, salon gani ko kayan asali na wasu. Za a bincika kayan da za su iya karya haƙƙi, a cire ko a maye gurbinsu bayan buƙata mai ma’ana.'] },
    { title: 'Alamun kasuwanci, sunaye da haƙƙin mallaka', paragraphs: ['Alamun kasuwanci, sunayen kamfanoni, kayayyaki da ayyuka, tambura da ayyukan da haƙƙin mallaka ya kare suna ga masu su. Ambato ba ya nuna amincewa, ɗaukar nauyi, haɗin gwiwa ko alaƙa sai idan an faɗa a sarari.', 'Ana wallafa rubutu na asali, lamba, tsarin shafi da kayan mutum don nuna aiki da koyo. Kada a kwafe su cikin kayayyakin kasuwanci ba tare da izini ba.'] },
    { title: 'Hanyoyin waje', paragraphs: ['Shafin na iya haɗawa da wasu shafuka, sada zumunta, ma’ajiyar lamba, sabis na saƙonni, kayan haɓakawa, masu binciken amfani da muhallan ayyuka. Masu su ne ke sarrafa su, kuma za su iya tattara bayanai bisa manufofinsu.', 'Mai shafin ba ya ɗaukar alhakin abun ciki na waje, yadda wasu ke kiyaye sirri ko samuwar sabis ɗinsu.'] },
    { title: 'Tuntuɓa', paragraphs: ['Don tambayoyi game da shafin, sirri, bayanan doka, cire abun ciki ko haƙƙi, yi amfani da hanyoyin tuntuɓa a shafin farko. Ku ba da isasshen bayani don gano shafi, abu ko matsalar.'] },
  ] },
});
