import { createAdditionalTranslation } from './createAdditionalTranslation.js';

// Translation draft; native-speaker review is recommended.
export const omTranslation = createAdditionalTranslation('om', {
  nav: ['Waa’ee koo', 'Muuxannoo', 'Taphoota', 'Quunnamtii'],
  labels: { navigation: 'Naanna’iinsa ijoo', mobileNavigation: 'Naanna’iinsa bilbilaa', openMenu: 'Tarree bani', closeMenu: 'Tarree cufi', theme: 'Bifa', system: 'Kan sirnaa', language: 'Afaan', signInInfo: 'Odeeffannoo seensaa', underDevelopment: 'Tajaajilli kun ammallee hojjetamaa jira', profile: 'Seenaa dhuunfaa', social: 'Geessitoota miidiyaa hawaasaa', summary: 'Cuunfaa ogummaa', cv: 'CV', work: 'Muuxannoo hojii', education: 'Barnoota fi koorsota', skills: 'Dandeettii fi meeshaalee', cvEn: 'CV Afaan Ingiliziitiin bani (PDF)', cvRu: 'CV Afaan Raashiyaatiin bani (PDF)', stack: 'Teeknooloojiiwwan', gameBoard: 'Dirree taphaa', score: 'Qabxii', gameOver: 'Taphichi xumurame.', restart: 'Irra deebi’ii jalqabi', counter: 'Lakkoofsa daawwannaa', personalSite: 'Marsariitii dhuunfaa kan daldalaa hin taane.', details: 'Odeeffannoo dabalataaf:', environments: 'Naannoowwan hojii' },
  greeting: 'Akkam jirtu hundi keessan!',
  summary: ['Baga gara marsariitii dhuunfaa hojii koo itti agarsiisuutti dhuftan.', 'Ani Full Stack QA Engineer dha; qorannoo harkaanii fi ofumaan raawwatamu kan frontend, backend, appii weebii fi moobaayila irratti xiyyeeffadha. Asitti CV koo, muuxannoo hojii, barnoota, koorsota xumure fi odeeffannoo quunnamtii koo argattu.', 'Taphoota biraawzarii yeroo boqonnaa koo akka yaalii teeknikaatti uumu illee taphachuu dandeessu. Marsariitiin kun akka isin gammachiisu nan abdadha.'],
  about: ['Bu’uura barnoota injinariingii qaba. Yuunivarsiitii Teeknikaa Mootummaa Moskoo Bauman irraa eebbifame; dizaayinii fi sagantaa meeshaalee elektirooniksii irratti xiyyeeffadhe.', 'Gara IT osoon hin ce’in, dameewwan injinariingii hedduu keessatti, sirnoota xiyyaaraa nama malee hojjetanii fi meeshaalee industirii dabalatee, hojjedheera. Pirojektoota tokko tokko irratti hojii garee qindeessaa, itti gaafatamummaa teeknikaa fi gurmaa’insaa fudhachaan ture.', 'Amma akka injinara QA tti hojjedha; dandeettii koo qorannoo ofumaan hojjetamuu fi saganteessuu keessatti guddisaa jira. Dogoggora arguu qofa osoo hin taane, sirna guutuu: UI, API, walitti hidhaminsaa fi bu’uuraalee isaa hubachuu barbaada. Qorannoon qulqullinaa fi salphina itti fayyadama oomishaa dhugumaan fooyyessuu qaba; sirna guutuu qofa ta’uu hin qabu.', 'Ogeessota QA haaraa nan barsiisa, nan gorsa. Qunnamtii gaarii, kaka’umsa fi itti gaafatamummaan hojjechuu nan kabaja.', 'Yeroo boqonnaa bishaan keessa qilleensa dabalataa malee cuuphamuu, miilaan deemuu, bidiruun imaluu fi ulfaatina qaamaa fayyadamuun sochii qaamaa gochuu nan jaalladha. Biyyoota garaagaraatti imaluus nan jaalladha.'],
  work: [{ period: 'Hagayya 2024 – amma', before: 'Waltajjii gurgurtootaa ', after: ' kan paakeejota bulchu ijaaruu.' }, { period: 'Caamsaa 2022 – Hagayya 2024', before: 'Pirojektii loojistikii maallaqa callaa Baankii VTB kan ', after: ' irraa, walitti qabuu maallaqaa ofumaan raawwachuu fi tajaajila ATM tilmaamuuf.' }],
  education: ['2024 – 2025 | Automation QA Engineer | Quality Academy.', '2023 – 2024 | Full Stack JavaScript Developer | Elbrus Bootcamp.', '2021 – 2022 | Manual QA Engineer | Quality Academy.', '2020 – amma | Koorsota Afaan Ingilizii | SkyEng, Duolingo, LinguaTrip.', '2008 – 2015 | Yuunivarsiitii Teeknikaa Mootummaa Moskoo Bauman | Faakaaltii Injinariingii Raadiyoo | Dizaayinii fi teeknooloojii oomisha meeshaalee raadiyoo-elektirooniksii | Qabxii giddugaleessaa: 4.05.'],
  skillTitles: ['Qorannoo', 'Ofumaan hojjechiisuu fi IDE', 'API fi deetaa', 'Bu’uuraalee fi galmeewwan', 'Moobaayilaa fi biraawzaroota garaagaraa', 'Oomishaa fi adeemsota'],
  life: { description: ['Game of Life sirna seelii ofumaan jijjiiramu kan ogeessi herregaa John Conway bara 1970 uume dha. Taphataa hin barbaadu: haalli jalqabaa guddina isaa murteessa; ajaja dabalataa hin barbaachisu. Dirreen taphaa seelota lubbuun jiranii yookaan du’an irraa ijaarama.', 'Jijjiiramni isaa seerota salphaa hordofa:'], rules: ['Seeliin lubbuun jiru olloota lubbuun jiran lamaa gadi yoo qabaate baay’ina xiqqaachuun du’a.', 'Seeliin lubbuun jiru olloota lubbuun jiran lama yookaan sadii yoo qabaate dhaloota itti aanu keessatti jiraata.', 'Seeliin lubbuun jiru olloota lubbuun jiran sadii ol yoo qabaate baay’ina garmaleetiin du’a.', 'Seeliin du’e olloota lubbuun jiran sirriitti sadii yoo qabaate lubbuun jiraata.'], interaction: 'Haala seelotaa jijjiiruuf cuqaasi. Bifa jalqabaa garaagaraa yaali, akkamitti yeroo waliin akka jijjiiramu ilaali.', controls: ['Tarreewwan', 'Tarjaawwan', 'Yeroo marsaa (sek.)'], cycle: 'Marsaa', repeatingState: 'Taphichi xumurame. Haalli duraanii irra deebi’ame.', allCellsDead: 'Taphichi xumurame. Seelonni hundi du’aniiru.', toggleCell: 'Haala seelii jijjiiri' },
  contactMessage: 'Gaaffii yoo qabaattan, imeelii yookaan miidiyaa hawaasaatiin na quunnamaa.', periods: ['Har’a', 'Torban 1', 'Ji’a 1', 'Waggaa 1', 'Waliigala'],
  privacy: { title: 'Dhuunfummaa fi odeeffannoo seeraa', lastUpdated: 'Yeroo dhumaa haaromfame: 20 Hagayya 2026', sections: [
    { title: 'Kaayyoo daldalaa hin taane', paragraphs: ['Marsariitiin dhuunfaa kun barachuu, hojii agarsiisuu, bashannanaa fi quunnamtii dhuunfaaf qophaa’e. Suuqii, gabaa, tajaajila kaffaltii, qumaara, tajaajila faayinaansii yookaan waltajjii gorsa seeraa, fayyaa yookaan faayinaansii ogummaa miti.', 'Marsariitichi daawwattoota irraa kallattiin galii argachuu, deetaa isaanii gurguruu yookaan taphoota biraawzarii, barruu, fuulota fi yaaliiwwan seenuuf kaffaltii gaafachuu hin kaayyeffatu.'] },
    { title: 'Itti fayyadama dhuunfaa fi barachuu', paragraphs: ['Kun pirojektii barumsaa fi hojii dhuunfaa agarsiisu dha. Koodiin, yaaliiwwan fuula itti fayyadamaa, taphoonni biraawzarii fi qabiyyeen ummataaf banaa dandeettii frontend, QA, qorannoo, ofumaan hojjechiisuu, dizaayinii fi injinariingii agarsiisuu danda’u.', 'Fakkeenyonni, mala taphaa, suuraaleen iskiriinii, wabii fi maqaan ibsuuf, barachuuf, qoruuf yookaan yaada beekamaa misooma weebii agarsiisuuf qofa fayyadu.'] },
    { title: 'Tajaajila kaffaltii fi gurgurtaan hin jiru', paragraphs: ['Marsariitichi kaffaltii hin raawwatu, deetaa kaffaltii hin sassaabu, maamilummaa kaffaltii yookaan oomisha dijitaalaa hin gurguru. Gara fuulduraatti tajaajilli daldalaa yoo dabalamuu ta’e, imaammanni kun osoo hin maxxanfamin dura haaromfamuu qaba.'] },
    { title: 'Deetaa daawwataa, herregaa fi quunnamtii', paragraphs: ['Marsariitichi galmee fi seensa herregaa qabaachuu danda’a. Deetaan galmee maqaa, maqaa masoo, imeelii fi jecha iccitii dabalachuu danda’a. Deetaa kaffaltii, ragaa eenyummaa yookaan deetaa dhuunfaa miira namaa tuqu beekaa hin gaafatu.', 'Fayyadamtoota galmaa’aniif spaamii, xalayaa beeksisaa yookaan beeksisa wal hin qabanne hin ergamu. Imeeliin dhimma herregaa, gargaarsa jecha iccitii, deebii kallattii fi beeksisa teeknikaa barbaachisaaf qofa fayyada.', 'Jecha iccitii marsariitii, appii, imeelii, baankii, miidiyaa hawaasaa yookaan sirna hojii biraa irra deebi’ii hin fayyadamin. Miidhaa jecha iccitii irra deebi’ame kan bakka biraatti dhangala’e, tilmaamame, hatame yookaan cabee irraa dhufuuf abbaa marsariitichaa itti gaafatamaa miti.', 'Jecha iccitii ofumaan deebisanii argachuun jiraachuu dhiisuu danda’a. Yoo barbaachise, odeeffannoo herregaa gaaffii adda baasuuf gahaa waliin gara antondorovs@gmail.com barreessaa.', 'Geessitoota alaa, miidiyaa hawaasaa, tajaajila ergaa yookaan imeeliin yoo quunnamtan, tajaajilli filattan deetaa akka ulaagaalee fi imaammata dhuunfummaa isaatti hojjeta.'] },
    { title: 'Xiinxalaa fi tajaajiloota qaama sadaffaa', paragraphs: ['Google Analytics, Yandex Metrica fi Microsoft Clarity tiraafikaa, raawwii, dogoggoraa fi walqunnamtii hubachuuf fayyadu. URL, bakka tilmaamaa deetaa neetworkii irraa, odeeffannoo biraawzarii fi meeshaa, seshinii, kukii yookaan mallattoo walfakkaataa, cuqaasuu, siqsuufi walqunnamtii biroo hojjechuu danda’u.', 'Xiinxalli qulqullina, salphina itti fayyadamaa, tasgabbii fi qabiyyee fooyyessuuf fayyada; daawwataa maqaan adda baasuuf, seenaa dhuunfaa gurguruuf yookaan beeksisa kaffaltii nama murtaa’e irratti xiyyeeffateef miti.', 'Lakkooftuun fe’iinsa fuulaa keessaa waliigala guyyaa UTC guyyoota 365 darbanii fi waliigala yeroo hundaa adda ta’e kuusa. IP, maqaa, imeelii, odeeffannoo biraawzarii, kukii, mallattoo meeshaa yookaan seenaa daawwannaa dhuunfaa hin kuusu.', 'Google, Yandex fi Microsoft deetaa akka ulaagaalee, imaammata dhuunfummaa fi qindaa’ina teeknikaa isaaniitti hojjetu. Qindaa’ina dhuunfummaa biraawzarii, ittisaa qabiyyee, too’annoo kukii yookaan filannoo keessaa bahuu dhiyeessaan qabu fayyadamuu dandeessu.'] },
    { title: 'Kukii fi kuusaa naannoo', paragraphs: ['Marsariitichi filannoo fuula itti fayyadamaa kuusaa biraawzarii keessatti kuusuu danda’a. Bifaa fi afaan filatame localStorage keessatti daawwannaa gidduutti kuufama.', 'Lakkoofsi yeroo fuulli guutuun fe’amu, haaromsa dabalatee, dabalu danda’a. Yeroon agarsiifamu foddaa yeroo socho’aa hanga guyyaa UTC ammaa ti; torban, ji’a yookaan waggaa kalaandarii miti. Daawwataa dhuunfaa adda hin baasu yookaan daawwannaa irra deddeebi’ame hin haqu.', 'Xiinxalli qaama sadaffaa kukii fi teeknooloojii walfakkaataa fayyadamuu danda’a. Hojii isaanii biraawzarii, naannoo, qindaa’ina dhuunfummaa fi qindaa’ina dhiyeessaa ammaa irratti hundaa’a.'] },
    { title: 'Pirojektoota taphaa fi mirga qaama sadaffaa', paragraphs: ['Taphoonni biraawzarii pirojektoota barumsaa dhuunfaa kan mala taphaa weebii fi yaada arcade beekamaa irraa ka’an dha. Vershinii seera qabeessa abbaa taphaa, jijjiirama hayyamame, irra-deebii daldalaa yookaan bakka bu’aa tapha jalqabaa miti.', 'Marsariitichi taphattoota fakkeeffamanii, maqaa daldalaa, maqaa taphaa, mallattoo, yaada, sagalee, bifa mul’ataa yookaan qabeenya jalqabaa kan namoota biraa irratti abbummaa hin gaafatu. Gaaffii madaalawaa booda, qabiyyeen mirga sirrii cabsuu danda’u ilaalamee ni haqama yookaan ni jijjiirama.'] },
    { title: 'Mallattoota daldalaa, maqaa fi mirga barreessaa', paragraphs: ['Mallattoonni, maqaan dhaabbataa, oomishaa fi tajaajilaa, loogoowwanii fi hojiiwwan mirga barreessaatiin eegaman abbootii isaanii ti. Maqaa kaasuun deeggarsa, maallaqaan deggeruu, shariikummaa yookaan hidhata hin agarsiisu, ifatti yoo hin ibsamne.', 'Barruun jalqabaa, koodiin, qindaa’inni fuulaa fi meeshaaleen dhuunfaa hojii agarsiisuu fi barumsaaf maxxanfamu. Hayyama malee gara oomisha daldalaatti hin waraabinaa.'] },
    { title: 'Geessitoota alaa', paragraphs: ['Marsariitichi gara marsariitii alaa, miidiyaa hawaasaa, kuusaa koodii, ergaa, meeshaalee misoomaa, dhiyeessitoota xiinxalaa fi naannoo pirojektiitti geessuu danda’a. Abbootii isaaniitiin bulu; akka imaammata isaaniitti deetaa sassaabuu danda’u.', 'Abbaan marsariitichaa qabiyyee alaa, hojii dhuunfummaa yookaan argamuu tajaajiloota qaama sadaffaaf itti gaafatamaa miti.'] },
    { title: 'Quunnamtii', paragraphs: ['Gaaffii marsariitii, dhuunfummaa, odeeffannoo seeraa, qabiyyee haquu yookaan mirgaaf geessitoota quunnamtii fuula jalqabaa fayyadamaa. Fuula, qabiyyee yookaan rakkoo adda baasuuf odeeffannoo gahaa kennaa.'] },
  ] },
});
