name: Deploy via FTP

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: vh404.timeweb.ru
          username: cg75134
          password: DexterMan1590!@&&&
          port: 21
          local-dir: ./
          server-dir: /public_html/