name: Deploy to Timeweb

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TIMEWEB_HOST }}
          username: ${{ secrets.TIMEWEB_USER }}
          key: ${{ secrets.TIMEWEB_SSH_KEY }}
          port: 22
          script: |
            cd ~/public_html
            git pull origin prod