name: FTP Login Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test FTP Login
        run: |
          curl -v ftp://vh404.timeweb.ru \
          --user "cg75134_anton:DexterMan1590" \
          --ftp-pasv \
          --connect-timeout 100