name: SFTP Test

on:
    workflow_dispatch:
    push:
        branches:
        - dev

jobs:
    test:
        runs-on: ubuntu-latest

    steps:
        - name: Test SFTP
        run: |
            sudo apt-get update
            sudo apt-get install -y sshpass
        
            sshpass -p "${{ secrets.TIMEWEB_PASSWORD }}" ssh -4 \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=20 \
            ${{ secrets.TIMEWEB_USER }}@${{ secrets.TIMEWEB_HOST }} \
            "echo SSH SUCCESS"