name: SFTP Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=20 \
            ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }} \
            "echo SSH SUCCESS"